### ISSUE TITLE
Doesn't wait for data before rendering

### ISSUE THREAD

**Issue by trainiac** [simoneb/axios-hooks#10]
I might be missing something but from reading the example and code these hooks don't actually allow you to render your data server side.  Yes, you can render the state of your app before you have data and these hooks will allow you to wait for data being fetched serialized to the client. However in order to achieve SEO goals you have to have the data rendered within your html.

In `graphql-hooks-ssr` they make a pass through the app render tree with `renderToStaticMarkup`.  That is what queues up the async requests.  They then wait for those async requests to finish and then make another render pass with `renderToString` with your pre-loaded data.

**Comment by simoneb** [comment]
That's a very good point, don't know how I missed it. I'm planning to look into this soon and release a new version that supports this scenario.
