### ISSUE TITLE
Why I'm getting 2 rendered using this hook, when component mounts?

### ISSUE THREAD

**Issue by gremo** [simoneb/axios-hooks#1061]
Plain simple:

```ts
import React from 'react';
import useAxios from 'axios-hooks';

export const Products = () => {
  const [{ data, loading, error }] = useAxios({
    url: 'https://dummyjson.com/products',
  }, { useCache: false });

  return (<div></div>);
}
```

The profiler shows 3 renders: first one it's the initial rendering. Second and third are from "**Hook 8 changed**". Why?

![image](https://user-images.githubusercontent.com/1532616/193009377-ab92ec52-f785-42fc-aad7-7535f89f88ac.png)

Hook 8 is:

![image](https://user-images.githubusercontent.com/1532616/193009521-34fa662e-8149-42f5-bd6b-94adfa94c13d.png)

**Comment by gremo** [comment]
@simoneb not sure about that. I use for testing another hook ([use-http](https://github.com/ava/use-http)):

` const { loading, error, data } = useFetch('https://dummyjson.com/products', {}, []);`

Why this hook only trigger 1 render? Two in total...

**Comment by simoneb** [comment]
can you provide a repro?

**Comment by gremo** [comment]
@simoneb I really appreciate your work, and OS software in general. For me, and maybe for you, it's more than a work. So I suggest you not to close an issue after five minutes, making assumptions about other's project/setup. 

Yes, I maybe a beginner in React but I'm not completely dumb.

1. Yes, I'm using React 18 (but you didn't know)
2. I'm not using strict mode, neither in that component nor up the tree (but you didn't know)
3. Either way, I would have noticed already the double rendering, elsewhere in my app

- `useAxios `[sandbox](https://codesandbox.io/embed/axios-hooks-3-rendering-o5t28e?fontsize=14&hidenavigation=1&theme=dark)

![useAxios](https://user-images.githubusercontent.com/1532616/193119324-59cd7885-5d17-451e-af82-1e7e737798fb.png)

- `useFetch `[sandbox](https://codesandbox.io/embed/use-http-2-rendering-z5tvqr?fontsize=14&hidenavigation=1&theme=dark)

![useFetch](https://user-images.githubusercontent.com/1532616/193119430-1907c2d8-bf3e-4469-aedf-19feaee12b72.png)

**Comment by simoneb** [comment]
I see your point, I had assumed React 18 was the cause. I've had a look at your repro and it looks legit. This seems to be causes by an improper handling of the state of the initial request.

Would you be interested in submitting a PR to fix this?

**Comment by gremo** [comment]
@simoneb thanks but I really can't, my experience with React isn't advanced yet! Hope to see a fix soon (or revert to a previous version maybe?)

**Comment by gremo** [comment]
Any  update @simoneb ?

**Comment by simoneb** [comment]
@gremo I didn't have a chance to look into it, but why don't you give it a go? I think it might be pretty simple. If the new state object is the same as the existing, don't change the state :)

**Comment by Paola3stefania** [comment]
Hello ! For what we have been researching with @cherrerotinoco It has to be with how the initialState its hanlded with manual false (automatic ), you can prevent this refetching error with `(manual: true) ` while waiting for a new PR
