### ISSUE TITLE
Custom reducer and default initial values

### ISSUE THREAD

**Issue by captrespect** [simoneb/axios-hooks#110]
Sometimes I need to modify the data after it's returned from the webservice before rendering.  It would be nice to pass in a custom reducer to handle this, unless you know of a better way.

It would also be nice to pass in a the initial data that is returned for rendering before the call is made.  Most of the time this would be an empty object or empty array.  It would save me from having to check for undefines in a bunch of places while rendering.

What do you think about adding this to the options object?
`{
     reducer: myCustomReducer,
     initialData: []
 }`

**Comment by simoneb** [comment]
Ok let's keep them as 2 different issues:

1) can you use an axios response transformer for this? https://github.com/axios/axios#request-config
2) it's been asked [before](https://github.com/simoneb/axios-hooks/issues/26) but the author didn't go as far as explaining how it would be beneficial. This wouldn't be a big change but I'm wondering if it's needed. Isn't the `loading` flag covering this already?

**Comment by captrespect** [comment]
The transformer for axios does look like a better place for that.  Thanks!

I did try using the loading flag, but I think because the form renders before the call is even made I think was getting the undefined for the data, and false for loading.  I'd have to check again.

Either way I was trying to get rid of the extra check before rendering.  It wouldn't matter if it was the loading flag or checking fo the data:

loading &&  data.map(...)
data &&  data.map(...)

With a default I could just say: 
data.map(...)

But in the end, it's probably a toss up between the complexity of adding another option vs just checking for data before rendering. It's probably not a bad idea to do the check anyway, incase of some other error.  

I guess I just talked my way out of it.

Thanks again.

**Comment by simoneb** [comment]
@captrespect on point 2) you're right, an additional option would make it slightly easier but I think it's redundant with what you can already do with the loading flag. I realize that the code you'd have to write if we had this option would be slightly nicer, but I don't find the alternative to be so bad as to justify having an additional option

**Comment by CloudPower97** [comment]
Hey, @simoneb @captrespect, I was just reading the repo issues and stumbled upon this.
To me, it seems that the second request can be accomplished simply using [`default parameters`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Destructured_parameter_with_default_value_assignment).
For example:
```javascript
const [
    { data = [{ userId: 1, title: "Default Parameter", completed: false }], loading, error },
    refetch
  ] = useAxios("https://jsonplaceholder.typicode.com/todos");
```

Until the new `data` get fetched from `axios` the default one will be shown.
This is not going to work while `refetching`, though.
