### ISSUE TITLE
How to mock axiosHook for testing?

### ISSUE THREAD

**Issue by explorer2309** [simoneb/axios-hooks#111]
This is not a bug, but I am not sure where else to ask the question - 

How can I mock the call to axios-hook for testing purposes using Jest?

Thanks!

**Comment by simoneb** [comment]
You can mock it in the same as you would mock anything else `jest.mock('axios-hooks')`

**Comment by explorer2309** [comment]
Thank you. I will investigate this.

**Comment by simoneb** [comment]
The default export is simply a function, so you can easily mock it and control its behavior in the standard Jest way:

```js
import useAxios from 'axios-hooks'

jest.mock('axios-hooks')

useAxios.mockReturnValue(...)
```

**Comment by dkershner6** [comment]
In case a more complex alternative is needed: https://www.npmjs.com/package/axios-hooks-mock
