### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by liting-yes** [simoneb/axios-hooks#1167]
I want to use **useAxios** with params, but got a type error, which I must set the **header** key :

<img width="869" alt="Screenshot 2023-01-19 at 20 37 40" src="https://user-images.githubusercontent.com/69500429/213445132-5916a419-e30c-4f07-a4b5-29f0f3eb2cd4.png">

why no replace the interface **AxiosRequestConfig** with **RawAxiosRequestConfig** ? I can't think of any other solution

<img width="683" alt="Screenshot 2023-01-19 at 20 37 58" src="https://user-images.githubusercontent.com/69500429/213445847-8948917b-6c40-478a-a96c-e212a99a2999.png">

confused, am I the only one who encounters this error ? Because I saw this way of writing in the official example :

<img width="747" alt="Screenshot 2023-01-19 at 20 37 08" src="https://user-images.githubusercontent.com/69500429/213445912-76a927a4-038f-49db-ae69-9105ba3c8b2a.png">

**Comment by simoneb** [comment]
which version of axios are you using?

**Comment by liting-yes** [comment]
> which version of axios are you using?

axios : 1.2.3
axios-hooks: 4.0.0

**Comment by bocceli** [comment]
I have the same problem with types as @liting-yes mentioned on the same versions.

**Comment by simoneb** [comment]
@liting-yes @bocceli the reason is that we haven't upgraded this package to be compatible with axios@v1. would you be interested in sending a PR to do this? you can see here that dependabot tried to bump it, but failed https://github.com/simoneb/axios-hooks/pull/1166

**Comment by liting-yes** [comment]
> @liting-yes @bocceli the reason is that we haven't upgraded this package to be compatible with axios@v1. would you be interested in sending a PR to do this? you can see here that dependabot tried to bump it, but failed #1166

ok, i can try，but there is no guarantee of completion time

**Comment by bocceli** [comment]
I went thought the axios code and they made some changes, but I believe we can fix our problem with this change.

**Comment by liting-yes** [comment]
I try to upgrade axis to v1, but sorry to encounter some unresolved issues: jest and axis can't work well together

on jest with v26, I don't find the way to resolve error about https://github.com/axios/axios/issues/5026
then I upgrade jest and ts-jest to latest, there have been many test failures unfortunately

**Comment by liting-yes** [comment]
if test can't pass, there is no point in upgrading axios
