### ISSUE TITLE
Uncaught TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by estoylive** [simoneb/axios-hooks#1171]
i am not sure what i am doing wrong but when trying to add this POST snippet I get this error! 

  const [{ postData, postLoading, postError }, executePost] = useAxios({
    
    url: 'http://localhost:3005/something',
    method: 'POST',
  });

and it marks the "const... " line as the source of the error.

**Comment by simoneb** [comment]
you can't just give the first item of the resulting array, which is an object, any property names, they are defined by the API. please see the quick start guide https://github.com/simoneb/axios-hooks#quick-start
