### ISSUE TITLE
How to configure SSR with NextJS?

### ISSUE THREAD

**Issue by pielegacy** [simoneb/axios-hooks#1195]
Howdy,

Big fan of the library however was wondering if there were any guides or pointers on how I'd go about configuring the SSR support with NextJS? Only as most of the examples I can find here are for more basic serverside rendering examples using express routes to handle SSR?

**Comment by EdMalovnek** [comment]
Looking at a similar use for the project im working on at the moment! Would love to get some more info on how to implement SSR with a NextJS app using axios hooks. 
Love ya work, ty

**Comment by lukaaaaaaaay** [comment]
Wow a lot of peeps doing SSR with Next.js and axios-hooks! I’m looking for the exact same thing. Any tips/examples would be very helpful
Thanks!

**Comment by simoneb** [comment]
Hey folks, apologies for the lack of response but as I'm the only maintainer here, it's hard to find the time to look into issues. Let's say SSR support is extremely limited at the moment, but the request makes sense and I'll try to look into it. There's no black magic though, so anybody is welcome to do so too. 

Meanwhile, if you really need support for SSR, please note that there are much better supported and feature rich libraries out there, and especially they have a richer community around them, such as https://tanstack.com/query/v3/ (and probably many others). Nevertheless I appreciate the interest in this project!
