### ISSUE TITLE
[Feature Request] Progress Percentage

### ISSUE THREAD

**Issue by iquirino** [simoneb/axios-hooks#128]
Any way to receive the current Progress and then attach it to a Progress Bar o something like that?

Thank you!

**Comment by simoneb** [comment]
You can do this with axios by providing appropriate configuration. https://github.com/axios/axios/blob/master/examples/upload/index.html

**Comment by iquirino** [comment]
This is not what i'm requesting...
See this:

const [{ data, loading, error, **progress** }, refetch] = useAxios({...});

**Comment by simoneb** [comment]
To do that we would have to attach a progress handler to every axios request. Doing it with axios is so simple that it doesn't feel like it deserves a specific feature.

**Comment by iquirino** [comment]
Can you show me a example of how to do this? I want to extend your hook with a new hook called useAxiosWithProgress, is it possible? Your solution is very nice, but this is a requested feature to my product...

**Comment by iquirino** [comment]
i don't want to interface directly with axios... This is the purpose that I am using your hook...

**Comment by iquirino** [comment]
Nice answer!!
