### ISSUE TITLE
Can't figure out how to attach completion event to PUT code

### ISSUE THREAD

**Issue by pkellner** [simoneb/axios-hooks#130]
With your example here:  https://www.npmjs.com/package/axios-hooks#manual-requests
```
function updateData() {
    executePut({
      data: {
        ...getData,
        updatedAt: new Date().toISOString()
      }
    })
  }
```
I want to to do work (update my own state) when the executePut completes. That is, something like passing a callback to `updateData(myCallback)` or `updateData().then(() => console.log('done'))`

Sorry for posting as an issue, but i've looked at the source and docs and it's not obvious how to do this.  When calling put with axios directly, I do something like:
```
    axios.put(`http://localhost:4000/speakers/${speakerRec.id}`, toggledRec)
      .then(function(response) {
        updateDataRecord(toggledRec);
      })
      .catch(function(error) {
        console.log(error);
      });
```
Is there anyway for me to do this with axios-hooks?

**Comment by simoneb** [comment]
`executePut` returns a promise, have you tried that?

**Comment by pkellner** [comment]
Thanks.  Didn’t know that or recognize in the source.  I’ll try that.

**Comment by pkellner** [comment]
Works perfect.  Thanks.

```
    executePut({
      url: `http://localhost:4000/speakers/${speakerRec.id}`,
      data: { ...speakerRec, favorite: !speakerRec.favorite }
    })
      .then(() => {
        completion();
      })
      .catch(() => {
        console.log(`Error putting: http://localhost:4000/speakers/${speakerRec.id}}`);
      });
```
