### ISSUE TITLE
"Uncaught runtime errors: Cannot read properties of undefined (reading 'data')" after upgrading to CRA 5.0.1 & Node 18

### ISSUE THREAD

**Issue by keremcanb** [simoneb/axios-hooks#1308]
Our app was previously working on CRA v4.0.1 and Node 16. But our DevOps team informed us that they will upgrading all Node versions to 18. But our app wasn't working only with Node 16, so I upgraded CRA to v5.0.1.

After the upgrade, we began getting "Uncaught runtime errors TypeError: Cannot read properties of undefined (reading 'data')" error messages. Some disappear after using optional chaining, some persist. 

We are using axios v0.21.1 & axios-hooks v2.6.3. I've upgraded to axios v1.4.0 & axios-hooks v4.0.0 to see if it helps, but we still get the same error.

Error message highlights this line at "/node_modules/axios-hooks/es/index.js":

`data: action.payload.data,`

**Comment by keremcanb** [comment]
> I believe the problem is that this library is not (yet) compatible with axios 1.x.

I'm getting the errors with axios v0.21.1 & axios-hooks v2.6.3 as well. This is our original setup, I upgraded them to see if it hepls but it didn't.

**Comment by simoneb** [comment]
I've just bumped the Node version we use in CI to LTS (meaning 18), and tests still pass, so I don't know what the problem might be. Any chance you can put together a repro which shows the issue?

**Comment by keremcanb** [comment]
> I've just bumped the Node version we use in CI to LTS (meaning 18), and tests still pass, so I don't know what the problem might be. Any chance you can put together a repro which shows the issue?

Thanks for your quick response and interest. 🙏 I'll try to put together a repo. 

Also, upon further investigation I've found out some cases that trigger the error. For example, we have a page that calls 3 services at the same time using "manual: false" and all services get cancelled now. Or there are some pages that call a service when an amount is entered at input field. If they are not debounced, they trigger the error. 

I know calling many services at the same time or not debouncing are bad practices. But they were working properly before, and because our codebase is massive, it'd be very difficult to find and fix all of them now.

**Comment by simoneb** [comment]
Thanks for the additional details. Unfortunately without a minimal reproduction I wouldn't be able to say what the issue might be, although the behavior you describe seems somewhat unexpected. If you could put together a minimal repro I could then check what might have gone wrong.

**Comment by keremcanb** [comment]
Finally I found the source of the problem. Latest version of webpack-dev-server has a new feature described as "Overlay displays unhandled promise rejection". This was causing the problem, downgrading to previous version solved it. Thanks again.
