### ISSUE TITLE
Not usable within the US?

### ISSUE THREAD

**Issue by timtucker-dte** [simoneb/axios-hooks#1331]
Unless I'm missing something, am I correct in the interpretation that the current anti-war license would preclude use by anyone who resides in the US, pays US taxes, or interacts with the US economy?

The parts that seem ambiguous:
- Does a past history of war constitute a history of war meet the criteria of "engages in"?
- Does "use of military force" as the US has done since World War II count as "war" even if there's no official declaration of war?"
- Assuming the US counts, does "financing" include anyone who interacts with the US economy, since a portion of all purchases from US corporations result in taxes that fund the US military?

**Comment by simoneb** [comment]
Thanks for asking, surely not many people bother checking out a license, let alone one which isn't standard.

This was indeed the intent of the ISC modification, and your understanding would be accurate. 

US is currently engaging in several conflicts across the globe although, to the best of my understanding, those military actions are not against those countries but rather in an attempt to restore those countries' legitimate governments.

Clearly I'm not a subject matter expert nor do I intend to be one, and neither am I trying to condone anybody's military actions against other peoples. 

This license modification was mainly tailored against Russia and in general countries invading other countries for the sake of invasion.

This is indeed a grey area, and unless you're intending to use this project for personal purposes I would definitely recommend that you pick something else. The good thing is that there is plenty of choice out there, starting with react-query to swc, and many more.
