### ISSUE TITLE
Error from a dynamically loaded uri

### ISSUE THREAD

**Issue by Hotmanics** [simoneb/axios-hooks#1431]
I am trying to use the useAxios hook, but the url I pass into it is undefined for the first few renders (as it pulls from the blockchain through another hook). This results in an error getting thrown in my VSCode console, but not in my browser console. The application continues to run fine and load everything properly after the first few renders, but Ideally I would like to not have an error thrown anywhere. Can't seem to find a way to deal with this. Any suggestions? Is this an unintended bug?

```
interface Nft {
  name: string;
  description: string;
  image: string;
}

export const MyComponent = () => {

    const { data: uri } = useUri(0); // uri: string | undefined

    const [{ data: json error, loading }] = useAxios<Nft>({ url: uri }); //error thrown here on first few renders
    //the error object is always undefined.

    return (
        <>
               <p>json.name</p>
               <p>json.description</p>
               <p>json.image</p>
        </>
    )
}
```

**Comment by simoneb** [comment]
The simplest solution would be to avoid rendering the component using the hook until the url has a value. Until then, trying to use the hook with an undefined url will cause an error.

**Comment by Hotmanics** [comment]
> The simplest solution would be to avoid rendering the component using the hook until the url has a value. Until then, trying to use the hook with an undefined url will cause an error.

how would that be possible? I thought hooks weren't able to be conditionally rendered.

**Comment by simoneb** [comment]
You nest components and render conditionally the one using axios-hooks depending on whether you have the url or not
