### ISSUE TITLE
Adding headers after axios instance is created

### ISSUE THREAD

**Issue by crofoot** [simoneb/axios-hooks#155]
As the title says I was wondering if there is a way to add headers after an instance is created? So for example before the user authenticates I don't have an authorization header. But once they login I want to inject the authorization header into the current instance. Any help would be greatly appreciated!

**Comment by simoneb** [comment]
There are a few ways to do this. By default `axios-hooks` used the default axios instance, which you can import anywhere else in code with `import axios from 'axios'`. In that case you can provide [global defaults](https://github.com/axios/axios#global-axios-defaults) or even use an interceptor.

Another way would be to use a custom axios instance and [`configure`](https://github.com/simoneb/axios-hooks#configure-cache-axios-) axios hooks to use it, then use again the axios instance defaults or interceptors to add your header.

**Comment by crofoot** [comment]
Thanks that worked! I had to add the header to the specific axios instance I created.
