### ISSUE TITLE
pass params to execute

### ISSUE THREAD

**Issue by AbdelhakAj** [simoneb/axios-hooks#176]
Hello, is there a way to pass params throw the execute/refetch function ?
if not I think this should be added.

``` 
const [{ data, loading, error }, getUser] = useAxios(
    'https://api.github.com/search/users?q=${username}',
    {
      manual: true
    }
);
```
I needed to pass username to the API url

```
<SearchBar
    onSearch={username => getUser(username)}
/>
```

thank you for creating this by the way

**Comment by simoneb** [comment]
The `getUser` function will take a request configuration that is the same as you would provide to axios. So:

```
const [{ data, loading, error }, getUser] = useAxios(
    // note I removed the query string from the url
    'https://api.github.com/search/users',
    {
      manual: true
    }
);

// them some time later

getUser({ params: { q: username } })
```

**Comment by flaviolivolsi** [comment]
@simoneb what about params in the URL? How to pass the param in that case?

Example:

```
const [{ data, loading, error }, getUser] = useAxios(
    'https://api.github.com/user/${username}',
    {
      manual: true
    }
);
```

**Comment by simoneb** [comment]
@flaviolivolsi one easy option would be to have `username` in the component state and use it in the Hook like this:

```
const [username, setUsername] = useState()

const [{ data, loading, error }, getUser] = useAxios(
   `https://api.github.com/user/${username}`,
    {
      manual: true
    }
);

// then somewhere in your code
setUsername('johndoe')
```

Depends on the use case but you get the idea

**Comment by muhsalaa** [comment]
Hi, I got the same issue here. I successfully fetched with params in options

```
{
    url: '/invitation/templates',
    method: 'GET',
    params: {type: typeState}
}
```

however, when I changed the typeState after choosing an option, and then refetch, I got the error below:

<img width="383" alt="Screen Shot 2020-10-18 at 21 40 56" src="https://user-images.githubusercontent.com/38155442/96371171-9ea98180-118a-11eb-9caf-d2bb253cde84.png">

thought my fetch is still continued (the result I want still returned), I find difficulty when using an error interceptor that rejects the promise.

```
export function interceptorResponseError(error) {
  const response = error.response?.data?.error || [
    {
      code: 'unknown',
      message: 'There is something wrong. Please try again later.',
    },
  ];
  return Promise.reject(response);
}
```

now my error alert in my component will be shown because of this error. How can I get rid of the error response in the first image? where does the error come from?

**Comment by simoneb** [comment]
The error you see is a cancellation error, meaning that you're doing multiple requests and one is canceling the other. This library does cancellation automatically.

This suggests a user-land bug. Can you provide a repro?

**Comment by muhsalaa** [comment]
actually, I'm able to solve the problem now. When you said it because of multiple requests, I realize that my code is wrong. My mistake is I use `refetch` after changing the state. 

```
const [type, setType] = useState('');

const [
    { data: vData, loading: vLoading, error: vError },
    refetch,
  ] = useRequest({ ...BuilderAPI.getInvitationTemplate, params: { type } });
```

I was thinking that I need to refetch after set a new type. Thanks for your response

**Comment by simoneb** [comment]
@muhsalaa you're welcome. Yes, when changing any of the parameters of the hook, the request is re-executed automatically without needing to invoke the execute function.

**Comment by morriq** [comment]
👍  for passing dynamic segment of url in manual invoke function.

something like:

`/api/users/:userId`

and then `run({ userId })`
