### ISSUE TITLE
Default value for data, possible?

### ISSUE THREAD

**Issue by fabn** [simoneb/axios-hooks#181]
Hi, thanks for your little gem. I was able to simplify my code from

```js
export default function InvoicesDashboard() {
    const [isLoading, setIsLoading] = useState(false);
    const [invoices, setInvoices] = useState([]);

    useEffect(() => {
        setIsLoading(true);
        api.get(`/invoices`)
            .then((data) => setInvoices(data))
            .finally(() => setIsLoading(false))
    }, []);
    
    // component rendering
    return <InvoicesTable invoices={invoices}/>
}
```

to this

```js
export default function InvoicesDashboard() {
    const [{data: invoices, loading}] = useApi('/invoices');
    
    return <InvoicesTable invoices={invoices || []}/>;
}
```

However I need to manually handle first render when data are not already loaded with `invoices || []`.

I was wondering if there's any way to specify a initial value for data as in `useState` hook. If not it would be a great addition to this project.

Thanks.

**Comment by simoneb** [comment]
This is not supported and will probably not be, considering how easy handling this case in user code is. See previous discussion in https://github.com/simoneb/axios-hooks/issues/110 and https://github.com/simoneb/axios-hooks/issues/26

**Comment by fabn** [comment]
Thanks,  I missed those ones. I solved with

```js
    const [{data: invoices = [],  loading}] = useApi('/invoices');
```
