### ISSUE TITLE
Feature request: Enable caching for manual requests

### ISSUE THREAD

**Issue by 8enSmith** [simoneb/axios-hooks#19]
When using manual mode (i.e. when the manual option is set to true) the execute function returned does not use the cache i.e.

```
return [
    state,
    configOverride => {
      return executeRequestWithoutCache(
        { ...config, ...configOverride },
        dispatch
      )
    }
  ]
```

It would be great if a user could choose to use the manual execute function which _does_ have caching enabled.

The scenario I have is where a user can undo an operation, which manually triggers execute, but I'd like to use a cached result instead of going back to the server.

Thoughts?

**Comment by simoneb** [comment]
Not sure I see understand the scenario. The assumption is that if you execute the query manually, then surely you want to execute it, right?

**Comment by 8enSmith** [comment]
> Not sure I see understand the scenario. The assumption is that if you execute the query manually, then surely you want to execute it, right?

So I have a page using a input control. When I enter data into the control it triggers an onChange event where the handler then makes use of execute. If a user deletes text from the control then execute (returned from useAxios) will correctly get called, however I'd like to use a cached result instead of going back to the server to recalculate the result.

**Comment by simoneb** [comment]
Okay that makes sense now. So this would be a breaking change if we change the manual query to use the cache by default. Let me think if there is a non-breaking way to introduce it, otherwise I'll have to bump major.

**Comment by 8enSmith** [comment]
Yes, either the behaviour of manual option would need to change or you'd need to introduce an additional option to control the caching.

The minor criticism I have (the work you've done on this repo is great!) is that I'd expect consumers (e.g. me!) would expect that the manual option just controls whether the hook runs automatically or not. I was surprised when I looked at the code to find that as well as doing this is also implicitly controls the caching behaviour. Hence a re-think in this area maybe warranted.

**Comment by simoneb** [comment]
@8enSmith fair point. the reason why it behaves like that is that historically that function was called `refetch` and it was used to, well, refetch the data of a query, and for that reason no caching in there was the only sensible behavior. Once the manual option was introduced that's not the only sensible behavior anymore though, but that's where it's coming from.

**Comment by simoneb** [comment]
@8enSmith can you have a look at #20 and let me know what you think? briefly, I extended the signature of the "refetch" function to accept an optional second parameter (the first is axios options overrides and needs to stay there) which allows to use the cache. it's off by default to avoid breaking changes and because I still think that it's the safe default

**Comment by 8enSmith** [comment]
I'd suggest giving users an option to opt in to caching for the standard or refetch behaviour, but its your call; I won't be surprised if someone asks for caching to be switchable for the standard hook behaviour.

I'll review the PR as it sounds like it'll fix the problem I have in my scenario.

**Comment by verekia** [comment]
Opened an issue at #33 for that scenario :)
