### ISSUE TITLE
Pagination example

### ISSUE THREAD

**Issue by SMJ93** [simoneb/axios-hooks#217]
Hey, great library!

Do you have a pagination example?

I'm trying to setup [Laravel pagination](https://laravel.com/docs/7.x/pagination).

Thanks

**Comment by SMJ93** [comment]
I've managed to get it working with the following:

```
const [currentPageNumber, setCurrentPageNumber] = useState(1);
const [previousTransactions, setPreviousTransactions] = useState([]);

// Endpoint
const [{data, loading}, postTransactions] = useAxios(
    {
      url: '/user/transactions',
      method: 'post',
    },
    {manual: true},
  );

// Fetch transactions on mount
  useEffect(() => {
    postTransactions();
  }, [postTransactions]);

// Fetch more transactions when scroll to end of flatlist
  const fetchMoreTransactions = () => {
    if (data?.pagination) {
      const nextPageNumber = currentPageNumber + 1;
      if (nextPageNumber <= data.pagination.last_page) {
        postTransactions({
          params: {
            page: nextPageNumber,
          },
        });
        setCurrentPageNumber(nextPageNumber);
        setPreviousTransactions(allTransactions);
      }
    }
  };

// Add new page of transactions to previous transactions
  const allTransactions = [...previousTransactions];
  if (data?.transactions) {
    allTransactions.push(...data?.transactions);
  }

// use allTransactions as data
return (
         <FlatList
            keyExtractor={(_item: any, index: number) => `${index}`}
            data={allTransactions}
            renderItem={({item}) => <TransactionGroup group={item} />}
            onEndReachedThreshold={0.5}
            onEndReached={fetchMoreTransactions} />
)
```

It just feels long / not very performant

**Comment by simoneb** [comment]
Why don't you use automatic requests (no `manual: true`) and provide the parameters to the request configuration using the values coming from the state? That way, whenever you change the state in a way that affects the request configuration the hook will request new data.

You will still need to handle adding the new data to the existing data, but this is more of an application logic concern, you're doing infinite scrolling rather than pagination.

**Comment by SMJ93** [comment]
Hey @simoneb!

Because I need to trigger the request from multiple places - pull down to refresh, on load screen, on scroll to end etc.

Yeah sorry, I always combine pagination + infinite scrolling. In this case I want to do infinite scrolling :)

I'll use the above implementation for now and close the issue, was just curious to see if there was an axios hook that would handle it for me.

**Comment by simoneb** [comment]
You can combine both approaches though. Clearly if you want infinite scrolling you will have to keep some local state. I've created two examples here:

- pagination: https://codesandbox.io/s/axios-hooks-pagination-1wk3u
- infinite scrolling: https://codesandbox.io/s/axios-hooks-infinite-scrolling-42nw6
