### ISSUE TITLE
Has no exported member "configure" and property "response" in Typescript

### ISSUE THREAD

**Issue by ArmPamKtu** [simoneb/axios-hooks#23]
In our terminal we get:
1. Property 'response' does not exist on type 'ResponseValues<any>' when using useAxios

![response_error](https://user-images.githubusercontent.com/36636744/62441971-eb0fc980-b75e-11e9-987c-d3a3eddca691.png)

2. The Module "../../path/node_modules/axios-hooks" has no exported member configure.

![configure_not_exported](https://user-images.githubusercontent.com/36636744/62441972-eba86000-b75e-11e9-83da-0e3574600f71.png)

**Comment by simoneb** [comment]
Released this together with test coverage for typings correctness in 1.3.0.
