### ISSUE TITLE
breaks on ie 11 from lru-cache dependency

### ISSUE THREAD

**Issue by jamescharlesworth** [simoneb/axios-hooks#234]
This repo seems to break on ie11 because its importing lru-cache which does not transpile down. I've added lru-cache to my babel config would prefer a different solution if you have one?

**Comment by simoneb** [comment]
lru-cache, as far as I can see, only requires some polyfills. Have you tried [CRA's polyfill for IE](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill)?

```
import "react-app-polyfill/ie11"
```
