### ISSUE TITLE
Does this working on react-native project  ?

### ISSUE THREAD

**Issue by bang88** [simoneb/axios-hooks#237]
I have an issue when I post a request with `{ manual:true }` options.  It's always throws an error and no data come back. 

What should I do.  Thank you very much.

**Comment by simoneb** [comment]
It does, I added an example to the readme: https://snack.expo.io/@simoneb/axios-hooks-react-native

**Comment by bang88** [comment]
with manual  options ? and doesn' t use cache

**Comment by simoneb** [comment]
> with manual options ? and doesn' t use cache

You can easily try the example and reopen this issue if it doesn't work. There's no reason why manual and useCache would make any difference.

**Comment by bang88** [comment]
Its really strange I can' t get any response from a post request.   I will try it using your example.

**Comment by bang88** [comment]
By the way your demo are running on a web browser. not a real device.

**Comment by bang88** [comment]
https://snack.expo.io/guVAwKceo This hook works well as expected  if I using `get` method.  but if  I using `post` and with manual on. it's not working anymore.

**Comment by bang88** [comment]
@simoneb I am sorry. Could you running it on a real device so you will get some error.  

Thank you.

**Comment by simoneb** [comment]
The demo is running in expo, which you can run on a real device. I just tried that and it works. Now, unless there's a difference running the app in expo or plain react-native I don't know, but I doubt it would make a difference as far as this hook is concerned.

**Comment by bang88** [comment]
https://snack.expo.io/guVAwKceo This snack doesn' t work too.  If you running it on ios or android.

**Comment by simoneb** [comment]
It works perfectly fine for me

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/83355803-3b15e780-a394-11ea-8005-4e920ee4875d.png)

**Comment by bang88** [comment]
It display an error.

**Comment by simoneb** [comment]
You're calling the API in the wrong way, the API doesn't support a body. I'm locking this conversation.
