### ISSUE TITLE
How to send headers

### ISSUE THREAD

**Issue by Jonofat** [simoneb/axios-hooks#238]
it isn't clear from the documentation (unless I missed it ) how to send headers. I need to send something like this:

`headers: { Authorization:  auth.token },`

**Comment by simoneb** [comment]
See [here](https://github.com/simoneb/axios-hooks#useaxiosurlconfig-options). The first argument to `useAxios` is the same as axios accepts. Either a string or a configuration object. With the latter, you can provide headers.
