### ISSUE TITLE
Is it possible to set state with the data?

### ISSUE THREAD

**Issue by Jonofat** [simoneb/axios-hooks#239]
```
  const config = {
    method: "get",
    headers: { Authorization: "Bearer " + auth.token },
    url: "http://localhost:8000/api/endpoint",
  };
  const [{ data, loading, error }] = useAxios(config);
 setOtherData(data)


```

Error: Too many re-renders. React limits the number of renders to prevent an infinite loop

**Comment by simoneb** [comment]
This is more a React question. The answer is yes, you can, you'll have to conditionally do that in a `useEffect` hook. If you do that at each render you'll get into an infinite loop.

**Comment by Jonofat** [comment]
Sure. If this question below is out of scope then let me know and I will close it off then as this shouldn't be for React questions. 

I couldn't use useAxios inside of useEffect as I got another error. I did the below and it works, but it doesn't seem like a good implementation on my part.

```
  const config = {
    method: "get",
    headers: { Authorization: "Bearer " + auth.token },
    url: "http://localhost:8000/api/admin/faq",
  };
  const [{ data, loading, error }] = useAxios(config);

  useEffect(() => {
    data && setItems(data);
  }, [data]);
```

**Comment by simoneb** [comment]
This would be the way to do it, but I wonder why you need this in the state in the first place.

**Comment by Jonofat** [comment]
The reason is because I am using [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) and there I need to do this:

`setItems((items) => arrayMove(items, oldIndex, newIndex));`

And if I try to put 'data' in there where I have the 'items' state, I get an error that it can't do what it needs to do. That is why I wanted to put data into my items state so I could use it there.

**Comment by simoneb** [comment]
You'll have to use the useEffect approach if you want to manipulate the data you're getting from the response, there's no other way that I can think of.

**Comment by simoneb** [comment]
I created an example [here](https://codesandbox.io/s/axios-hooks-react-sortable-hoc-eo3oy)

**Comment by Jonofat** [comment]
Thank you!
