### ISSUE TITLE
data is undefined when using custom cancel tokens

### ISSUE THREAD

**Issue by Songkeys** [simoneb/axios-hooks#257]
I wrote interceptors to prevent repeated requests using cancel tokens. But I found that when I tried to call `cancel()`, the `data` in `useAxios`'s return is always `undefined` even if the request has been accomplished.

Here's my script for axios:

```ts
let pending: { key: string; cancel: Function }[] = [];
const CancelToken = Axios.CancelToken;
const generateRequestKey = (config: AxiosRequestConfig) => {
  return config.url + "&" + config.method;
};
const removePending = (config: AxiosRequestConfig) => {
  for (let i = pending.length - 1; i >= 0; i--) {
    if (pending[i].key === generateRequestKey(config)) {
      pending[i].cancel("cancel a request");
      pending.splice(i, 1);
    }
  }
};

axios.interceptors.request.use(config => {
    removePending(config); // remove last pending same
    const source = CancelToken.source();
    config.cancelToken = source.token;
    pending.push({
      key: generateRequestKey(config),
      cancel: source.cancel
    });
    return config;
});

axios.interceptors.response.use(response => {
    removePending(response.config); // remove this finished one
    return response;
});
```

**Comment by simoneb** [comment]
I'm not sure what you're trying to do here, but axios-hooks has built-in cancellation, meaning that it will cancel outstanding requests in case a new one is started.

Is your requirement that of being able to provide custom cancellation logic?

**Comment by Songkeys** [comment]
My logic is to cancel "multiple duplicated requests". For example, a user called `"/home"` again when the previous one hasn't been called yet.

The reason is that I have another part of logic to "hang the axios" and "push all incoming request configs into a pending array" to ask for an authorization for the current user first. The custom cancellation logic here is to help remove duplicated request during this period.

> it will cancel outstanding requests in case a new one is started.

I still don't know what the built-in cancellation does. What does it mean by "outstanding requests"? Maybe we should state it clearly in the docs as well?

But anyway, I believe the built-in one and my custom one has some conflicts.

**Comment by simoneb** [comment]
The way axios-hooks behaves is that it cancels requests that it started. I feel what you're trying to do here is the same, so I'm wondering if you need a custom cancellation mechanism in the first place.

If you do not provide your custom cancellation mechanism, do you see requests being canceled automatically by axios-hooks if you start a request when another (started from the same instance of the hook) is still in progress?

**Comment by Songkeys** [comment]
I removed my custom cancellation method, it seems working in my use scene! Thank you so much! (I remember when using axios alone, it doesn't.)

> it cancels requests that it started

What I leant from the source code is that it cancels on component unloading. Is there any other situation that causes cancellation?

**Comment by simoneb** [comment]
The useEffect cleanup function is not only called when the component unmounts, but also before the hook re-executes because the dependencies changed. So, the behavior it that it cancels any request. Note that I'm making some changes to this behavior right now to make it more robust, addressing #250 .

**Comment by Songkeys** [comment]
Thank you so much!

Maybe it's good to include these notable built-in behaviors as features in README. Otherwise, some developers might implement it themselves just like me.
