### ISSUE TITLE
data is undefined when modifying the return value in response interceptor

### ISSUE THREAD

**Issue by Songkeys** [simoneb/axios-hooks#258]
My response from my server will always have a `data` property to wrapper the true return value. (e.g. `{data: {...}}`)

So I need this interceptor to reduce my work (of extra object destructuring):
```js
axios.interceptors.response.use(response => response.data);
```

But this will turn `data` value in the return of `useAxios` into `undefined`.

**Comment by simoneb** [comment]
I can think of two possible issues you're having:

- the interceptor should not return a different shape, it should modify the data property of the response, but keep returning the response
- you may be configuring the interceptor multiple times

See this [example](https://codesandbox.io/s/axios-hooks-axios-interceptors-mcyuq).

**Comment by Songkeys** [comment]
I got your idea. The issue is related to the first one.

When using axios alone before, I didn't think about "shape". You are right. I should keep returning the response for axios-hooks because it uses other properties on the `response` value.
