### ISSUE TITLE
Feature Request: refetch options to override base options

### ISSUE THREAD

**Issue by LuisCarrilloR** [simoneb/axios-hooks#262]
Hello, is it possible to add an option or to make the library work by default overriding the default options when calling the refetch function?. The merge is working great but looking at some use cases I think it would be useful to override the defaults once the merge is done.

Sources:
- [Apollo documentation](https://www.apollographql.com/docs/react/data/queries/#refetching): _You can optionally provide a new variables object to the refetch function. If you don't (as is the case in the following example), the query uses the same variables that it used in its previous execution._

Use case example: 
1. Table component triggers the refetch function on mount with the pagination data.
2. User changes page to 2.
3. Refetch is called with the new pagination data.
4. External action (added something new) 
5. Refresh the table data is required without pagination data. (expect just to use refetch to repeat the last one)

As you can see in step **5**, it would be nice to repeat the latest request without options but using the latest ones.

Test:
If you click the Button **refetch** and then **external refetch** the expected data should be the one retrieved in the previous request (the one retrieved on the refetch button). [Test here](https://codesandbox.io/s/axios-hooks-makeuseaxios-melc3?file=/src/index.js).

**Comment by simoneb** [comment]
There are simpler ways to do this, here's one:

Don't use manual requests and store the parameters in the component's state, then you can reference them in useAxios and whenever they change a new request will be triggered. [Example](https://codesandbox.io/s/axios-hooks-pagination-in-state-no-manual-m14nk).

Alternatively, you can keep using manual requests and still store the parameters in the component's state, they will be used when refetching.

**Comment by LuisCarrilloR** [comment]
Yeah I agree both options can work, but I am not sure if handling the options state outside the hook is the way to go. I think the only one in charge of handling the request (request options in this case) is the hook itself.

Please let me know what you think or if you are accepting PRs for this request. Thanks!

**Comment by simoneb** [comment]
You can definitely suggest a change here, but just so you know, I'm not very keen in keeping any sort of state inside the hook, apart from the global cache.

Considering that the way the hook works (retrigger request when request configuration changes) makes it very simple to implement this, I am currently not in favor of supporting this scenario inside the hook itself, also considering that it may be a breaking behavior.

**Comment by simoneb** [comment]
Stale, closing.
