### ISSUE TITLE
Question: how to execute code after getting a response?

### ISSUE THREAD

**Issue by Guguskis** [simoneb/axios-hooks#28]
I am beginner developer and this might be a dumb question. All I want is to call a function after getting a response.
My current solution is to use useEffect:
```
useEffect(() => {
    if (!postLoading) {
        // Calling my function
    }
}, [postLoading]);

```

I don't know if that is a good way or not, but I would prefer to do it something like this:
```
executePost({
    data: {
        // My data
    }
}).then( /*Calling my function*/);
```
The second solution in VS Code spits out error "Property 'then' does not exist on type 'void'.".
Is there a way to do this with axios hooks?

**Comment by simoneb** [comment]
the hooks way would be to use effect, but it should already be possible to await the promise returned by the refetch function. check out [this example](https://codesandbox.io/s/wizardly-saha-4vshd).

**Comment by Guguskis** [comment]
Thank you, this example helped :)

**Comment by Lekha30** [comment]
The codesand link above isn't working. I want to do a refetch triggered automatically after a POST.
