### ISSUE TITLE
Possible to remove @babel/runtime as a dependency?

### ISSUE THREAD

**Issue by dkershner6** [simoneb/axios-hooks#298]
This library is so tiny, that, percentage-wise, this could make a big difference.

https://github.com/simoneb/axios-hooks/blob/0ebdae8e1d9bb6115654e08dc43d7e7628e74ad6/package.json#L38

The package size is currently 18KB, but the actual code + `lru-cache` are only about 7KB combined...

I am not sure what it is being used for, however, or what would be required, just wanted to voice an opportunity.

**Comment by simoneb** [comment]
I think we might be already doing the right thing by using `@babel/runtime` as a dependency (needed for async/await support) and `@babel/plugin-transform-runtime` as a devDependency.

This should allow a host application using ES modules to dedupe  the `@babel/runtime` code.

In practice, I didn't check that this is really happening.

**Comment by simoneb** [comment]
@dkershner6 I checked by doing a simple repro with CRA. When you use async/await, CRA will include the babel runtime. When also adding axios-hooks, the babel runtime is deduped.

You can try it yourself by doing these 4 combinations:

- CRA no async/await -> no babel runtime
- CRA with axios-hooks -> babel runtime
- CRA with async/await -> babel runtime
- CRAP with axios-hooks and async/await -> deduped babel-runtime

**Comment by dkershner6** [comment]
I was thinking more along the lines of react native, where they don't use Babel runtime at all, but I checked, and they do use regenerator runtime, which is the largest dependency of Babel runtime.

Next.js also uses Babel runtime as well.

Agree that this is not worth worrying about and ES2018 support is worth it.
