### ISSUE TITLE
SSR does not work

### ISSUE THREAD

**Issue by pupudu** [simoneb/axios-hooks#30]
Hello there, thank you very much for the efforts put into this so far.

I played with this library today and I am puzzled if this actually works on the server-side. I'll explain what I tried so far. Perhaps, I did something wrong. Perhaps, it's an issue with the bundler setup. Perhaps, React is not mature enough to support this functionality.

1. First, I created a new app with Razzle: https://github.com/jaredpalmer/razzle
2. Then, I did the configurations for axios-hooks as instructed. 
3. I fetched data from: https://www.mocky.io/v2/5185415ba171ea3a00704eed and added it to the component body

Now the application works well. The component with the hook looks like this:

```typesccript
function Home() {
  const [{data, loading, error}] = useAxios({url: 'https://www.mocky.io/v2/5185415ba171ea3a00704eed'});

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error!</p>

  return (
    <div>
      Home
      {JSON.stringify(data)}
    </div>
  );
}
```

Then I added a `console.log` to the static markup generated from the react-dom `renderToString` method. Sadly, the only thing I see on the server-side is:
```typescript
<p>Loading...</p>
```
This gives me the feeling that actual markup with data is never generated on the server-side. Instead, the server-side markup is generated for the loaders, then the actual data hydration happens on the client-side. If that is the case, I think it partially defeats the whole purpose of using server-side rendering. 

Happy to discuss/clarify/give more information etc. 

Thank you again for all the effort put into this library.

**Comment by chris-visser** [comment]
Figured the same thing. Its only pre-loading the data to prevent a client fetch.

**Comment by sieglingm** [comment]
Also thanks from my side for your effort and work. But I agree with above statements: That is not server side rendering. For that the html code has to be rendered with data already on server side which is not the case. The data fetching on server side works, the cache is correctly filled on client side on the initial prerendered page. 
But I have another problem: The option 'useCache=true' does not seem to work, the fetch is still executed again on client side with date=undefined and loading=true.

**Comment by simoneb** [comment]
I am aware of this issue, I've reproduced it but I've postponed work on it because I figured it would require a considerable rewrite of the caching layer, which is now relying on axios's built-in caching mechanism and which cannot work in SSR scenarios. I'm planning to work on this at some point, but I don't know when yet. Of course, any PR is more than welcome and I'm available to provide implementation hints if anyone's interested in picking this up.

**Comment by simoneb** [comment]
> Also thanks from my side for your effort and work. But I agree with above statements: That is not server side rendering. For that the html code has to be rendered with data already on server side which is not the case. The data fetching on server side works, the cache is correctly filled on client side on the initial prerendered page.
> But I have another problem: The option 'useCache=true' does not seem to work, the fetch is still executed again on client side with date=undefined and loading=true.

If this is a different issue, can you please file a new one?

**Comment by bananamboon** [comment]
hello guys, are there any developments for this issue?

**Comment by simoneb** [comment]
@bananamboon no developments unfortunately. I don't have enough time to spend on this myself and I would be happy to see a contribution to address this issue.

**Comment by anh072** [comment]
if the data is not fetched and HTML is not rendered on server side, then its not really SSR. the README says it supports SSR which is very misleading.

Any follow-up on this issue
