### ISSUE TITLE
Cleanup after response

### ISSUE THREAD

**Issue by sainer** [simoneb/axios-hooks#31]
When I manually execute request and useAxios return me const object it is filled with response data until next response (next response change response data). For example I want to check response status code, but what if my functional component is next rendered by an another cause and I dont't want to checking reponse again. I want only one response checking durin first render after reponse but not in next renders wchich are not related to axios (I have useEffect also and redux store reading in it). So is some cleanup procedure for cleaning axios response for example in if clause after reading response.

**Comment by simoneb** [comment]
Wouldn't relying on the `loading` flag allow you to carry out this logic?

**Comment by sainer** [comment]
It depends on when loading flag is set to false. Currently I'm using useState and my own state flag to check is component rendering after successful request. I do it in if clause. I'm checking response.status and if it's as 200 code then I'm setting this flag to true. Initially this flag is also true, and it's set to false only if the app manually execute HTTP request (axios manual method)  - I do it after user click the button to send provided data to API.

**Comment by simoneb** [comment]
Can you provide an example? Explaining code in words is not easy to follow.

**Comment by sainer** [comment]
This is my actual sample code
`
.......
  const [requstFinished, setReqestFinished] = useState(false);
  const tickerInput = props.channel.ticker_text
  const [ticker, setTicker] = useState();
  useEffect(() => {
      setTicker(props.channel.ticker_text);
  }, [props.channel.ticker_text])
  const [ { response: putResponse, loading: putLoading, error: putError }, executePut ] = useAxios(
    {
      url: ROOT_BACKEND_URL + "channels/" + props.channel.id,
      method: "PUT",
      headers: HTTP_HEADERS
    },
    { manual: true }
  );
  const handleRequestSave = () => {
    executePut({ data: JSON.stringify({ tickerText: ticker }) });
    setReqestFinished(false)
  };
  if (putLoading)
 ///here I have a spinner
  if (putError) {
    if (putError.response) toast(putError.response.status, { type: "error" });
    else toast("Error", { type: "error" });
  }
  if (putResponse && !requstFinished) {
    if (putResponse.status==200) {
      toast("Success", { type: "success" });
      setReqestFinished(true)
    }
  }
return(
...........`

**Comment by simoneb** [comment]
executePut will return a promise that will tell you when the request has completed. will that help?

**Comment by sainer** [comment]
Yes. It's perfect solution. Thanks for help. I changed my code and it works fine
