### ISSUE TITLE
Server-side memory leak

### ISSUE THREAD

**Issue by ckeeney** [simoneb/axios-hooks#311]
I have identified a memory leak in 2.0 and 2.1 and am rolling back to 1.11 in production.

I have created a repository to reproduce the issue here: https://github.com/ckeeney/axios-hooks-mem-leak

**Comment by simoneb** [comment]
Thanks for the report and for the detailed repro. I think I identified where the memory leak comes from, which is a consequence of the different caching mechanism introduced in 2.x.

**Comment by ckeeney** [comment]
Is it possible to disable the server side behavior of this package?  A hook making requests server-side is pretty unexpected and I'd just prefer if this hook only worked client-side.

I looked for alternative packages, but this is the most mature axios hook package I could find.

**Comment by simoneb** [comment]
You're right and long overdue. I don't have enough time to fix the problem itself but I introduced a way to disable ssr. See https://github.com/simoneb/axios-hooks/pull/374

**Comment by simoneb** [comment]
@ckeeney please let me know if this works for you and I'll release it as 2.3.0.

**Comment by ckeeney** [comment]
The change looks great to me.  Thanks.

**Comment by ckeeney** [comment]
I'm not sure if this memory leak is still an issue, I haven't used a 2.x release since I opened this issue, but I do plan on using 2.3.x in the near future.  Feel free to close this if the memory leak issue has been solved.

**Comment by simoneb** [comment]
Unfortunately it still is, this change is a workaround to let you disable SSR but also allows to set other options globally.

**Comment by ckeeney** [comment]
That's alright.  Given the memory leak issue in v2, it may be best to just default SSR to false.  I know that's kind of a breaking change, but v2 is not really usable in production with the memory leak anyways IMO.

**Comment by simoneb** [comment]
That's correct but I didn't want to release a major as I'm joking to fix the issue at some point. This release allows you to turn SSR off and bypass the issue until then.
