### ISSUE TITLE
Usage with Redux?

### ISSUE THREAD

**Issue by boxdox** [simoneb/axios-hooks#315]
I don't know if this been asked before, but I want to integrate it with redux. 
I tried to use `{ manual: true }` so that I can make the request on page load and store the data into redux. But this always results in `loading` to be `false`, hence React throwing error that `data` is undefined.

```jsx
const [{ data, loading, error }, execute] = useAxios(
    {
      url: 'getProfile',
      method: 'POST',
    },
    { manual: true }
  )

  useEffect(async () => {
    const t = await execute()
    console.log(t)
  }, [])
```

What am I doing wrong here? Should I maintain my own `loading` state?

Another question, Since this is a react hook, I don't see a possibility of integrating it directly into redux (thunk) action. So I think maybe I should update redux with values returned from the hook?

**Comment by simoneb** [comment]
The loading state works fine when doing a manual execution of the request, see [example](https://codesandbox.io/s/2oxrlq8rjr).

As for storing results in redux, since this keeps its own state using redux would be redundant. I suggest that you either use this or redux, not both.

**Comment by boxdox** [comment]
> The loading state works fine when doing a manual execution of the request, see [example](https://codesandbox.io/s/2oxrlq8rjr).

That is because the hook is executed once, so there's data in it. I don't want it to run unless I explicitly call the refetch/execute.

> As for storing results in redux, since this keeps its own state using redux would be redundant. I suggest that you either use this or redux, not both.

I need redux in the application, so I think I should look at some other package or write my own. Got any advice?

**Comment by simoneb** [comment]
> > The loading state works fine when doing a manual execution of the request, see [example](https://codesandbox.io/s/2oxrlq8rjr).
> 
> That is because the hook is executed once, so there's data in it. I don't want it to run unless I explicitly call the refetch/execute.
> 

It works fine even using the manual option, check for yourself.

> > As for storing results in redux, since this keeps its own state using redux would be redundant. I suggest that you either use this or redux, not both.
> 
> I need redux in the application, so I think I should look at some other package or write my own. Got any advice?

If you're using redux this package is unnecessary, there are possibly many approaches you can use but a fairly standard one is to use plain axios with redux-thunk

**Comment by boxdox** [comment]
@simoneb For me, `loading` is always false. No idea why.

Anyways, thanks for the help, I know this is off-topic, so I will close this issue.

**Comment by simoneb** [comment]
> @simoneb For me, `loading` is always false. No idea why.

Can you please check the linked example and try to reproduce it there? There it is working fine, but maybe you hit a edge case or something.
