### ISSUE TITLE
Testing: How to test component which uses useAxios when using TypeScript in Jest?

### ISSUE THREAD

**Issue by 8enSmith** [simoneb/axios-hooks#32]
Ok, this is not an issue with the library, it's a question on how it can be mocked when using it in a React component. I'm using TypeScript which appears to be further complicating the matter (for me anyhow!)

I've created a question on StackOverflow too as can be seen [here](https://stackoverflow.com/questions/57926493/how-to-test-a-component-which-is-using-a-custom-react-hook).

I'd have thought this would be trivial but am finding it tricky!

**Comment by simoneb** [comment]
This question is not relevant to the project. There's nothing specific to axios-hooks that you need to do to test a component which uses it.
