### ISSUE TITLE
Discussion - Refetch Cache

### ISSUE THREAD

**Issue by kentongray** [simoneb/axios-hooks#346]
Hey! First of all I really like this library we've implemented it in our app and think it provides a great flexible model for all of our API calls. When using the library I found myself wanting a feature and apologies if I'm misreading the docs but would love your opinion and if this is something that would make sense to submit a PR for.

The concept is Cache & Refetch - The way I'd like to use the cache is to have it use the cache to give an immediate response but then trigger the request and replace the data returned. That way you have a very fast initial load but also can update the data if is no longer valid. Ideally it could also do a comparison to see if it actually changed (but that might require a library or compare function) to remove unneeded state changes.

**Comment by dkershner6** [comment]
Sounds a lot like `useSwr`.  You can always use that lib with an `axios` fetcher.

I am not sure something like this belongs in the core library, which should stay as simple as possible, but layering something over the top of `useAxios` wouldn't be that difficult.

- With that, the cache part is done for you.
- The refetch part, you can call `refetch` and ignore the `loading` status.
- When `loading` goes from true to false, perform a compare (`useMemo` using `JSON.stringify`?), update something if it changed (`state`?)

`axios-hooks-swr`?

**Comment by simoneb** [comment]
This is an interesting discussion.  There is nothing being done explicitly around this because the rationale behind this library is to have something simple readily available. 

I didn't know about `useSwr`, thanks for mentioning it @dkershner6. I can see in the docs that it has plenty of options which I'm not sure fit in this library instead.

Nevertheless, I put together an example to kickstart a discussion around this. Even though it's not supported right now, it doesn't look like SWR is too difficult to implement manually.

https://codesandbox.io/s/axios-hooks-swr-1yz0x?file=/src/index.js

I'd like to hear your thoughts on this

**Comment by dkershner6** [comment]
>  Ideally it could also do a comparison to see if it actually changed (but that might require a library or compare function) to remove unneeded state changes.

Adding this to the example would achieve this goal:

```js
const dataString = useMemo(() => JSON.stringify(data, null, 2), [data]);
const displayData = useMemo(() => dataString, [dataString]);
```
(string comparisons are based on the contents, so `displayData` only would run on content changes, `dataString` would run on all changes)

**Comment by kentongray** [comment]
I like this approach a lot simoneb, I may just try to implement it in our code since we already abstract over axios-hooks. That being said if you have any interest in making it "standard" I'd be happy to submit it. Feel free to close this issue!

**Comment by simoneb** [comment]
I'm leaving this open because I'm not against having this behavior in the library, but unlikely that I will get around to implementing this anytime soon. If somebody wants to contribute this, happy to review it. If we do, it should be introduced in a reasonably non-intrusive way.

**Comment by dandin84** [comment]
Hi, thanks for the library!

This is my implementation according to the example mentioned. It actually seem to work :)

The only issue that I am struggling with is if I switch between pages before the refetch done, I am getting errors.
How would you suggest I should handle the unsubscribe/cancellation to prevent those errors?

**The implementation:**
![image](https://user-images.githubusercontent.com/6383184/118289660-3fbca880-b4de-11eb-8ba0-97a758903776.png)

The error:
![image](https://user-images.githubusercontent.com/6383184/118289831-67ac0c00-b4de-11eb-8f31-978d81ec64b5.png)

![image](https://user-images.githubusercontent.com/6383184/118289988-988c4100-b4de-11eb-9ec8-e6fe0305b7ec.png)

**Comment by simoneb** [comment]
You can simply swallow that error

**Comment by dandin84** [comment]
Cool, thats what I did, thanks :pray:
