### ISSUE TITLE
How to mock axios response if we use axios-hooks?

### ISSUE THREAD

**Issue by LiaoJimmy** [simoneb/axios-hooks#35]
Hello, I try to mock axios response by:   
@react-mock/xhr: https://github.com/ctimmerm/axios-mock-adapter  
axios-mock-adapter: https://github.com/ctimmerm/axios-mock-adapter
and enve jest mock: https://jestjs.io/docs/en/mock-functions#mocking-modules  
They all mock axios response failed.

Do you have any example to mock axios if we use axios-hooks?

### My example code:
```javascript
// AxiosHooks.jsx
import React from 'react';
import useAxios from 'axios-hooks';

export default () => {
  const [{ data: getData, loading: getLoading, error: getError }] = useAxios(
    'bins/820fc',
  );

  const [
    { data: putData, loading: putLoading, error: putError },
    executePut,
  ] = useAxios(
    { url: 'bins/820fc', method: 'PUT' },
    { manual: true },
  );

  function updateData() {
    executePut({
      data: {
        ...getData,
        updatedAt: new Date().toISOString(),
      },
    });
  }

  if (getLoading || putLoading) return <p>Loading...</p>;
  if (getError || putError) return <p>Error!</p>;

  return (
    <div>
      <button type="button" onClick={updateData}>update data</button>
      <pre>{JSON.stringify(putData || getData, null, 2)}</pre>
    </div>
  );
};
```

And here is the test file.
```javascript
import React from 'react';
import { render, waitForElement, fireEvent } from '@testing-library/react';
import axios from 'axios';
import MockAxios from 'axios-mock-adapter';

import AxiosHooks from './AxiosHooks';

const mock = new MockAxios(axios);

describe.skip('<AxiosHooks />', () => {
  it('should get server time', async () => {
    mock.onGet('/bins/820fc').reply(200, {
      updatedAt: '2019-09-29T04:46:23.256Z',
    });
    const { getByText } = render(<AxiosHooks />);

  // Failed! It will get now time.
    await waitForElement(() => getByText('2019-09-29T04:46:23.256Z'));
  });

  it('should get updated server time', async () => {
    mock.onGet('/bins/820fc').reply(200, {
      updatedAt: '2019-09-29T04:46:23.256Z',
    });
    mock.onPut('/bins/820fc').reply(200, {
      updatedAt: '2019-09-29T04:46:30.256Z',
    });
    const { getByText } = render(<AxiosHooks />);
    const updateButton = await waitForElement(() => getByText('update data'));

    fireEvent.click(updateButton);

    // Failed! It will get now time.
    await waitForElement(() => getByText('2019-09-29T04:46:30.256Z'));
  });
});
```

**Comment by simoneb** [comment]
If you're using this library don't mock axios, mock this library via jest

**Comment by LiaoJimmy** [comment]
Thanks. I'll try to mock axios-hooks response array.

**Comment by tgfischer** [comment]
You should be able to mock `axios` and test it with `axios-mock-adapter` and `@testing-library/react-hooks`. In my project I wrap this hook in a custom request hook, which makes it easy for me to switch libraries under the hood without breaking all my tests.

To mock `axios`, try something like this

```js
import { renderHook, act } from "@testing-library/react-hooks";
import axios from "axios";
import useAxios from "axios-hooks";
import MockAdapter from "axios-mock-adapter";

const mockAdapter = new MockAdapter(axios);

describe("request tests", () => {
  const url = "/api/my/request";
  const data = { message: "success!" };

  beforeEach(() => mockAdapter.reset());

  it("should make a GET request", () => {
    mockAdapter.onGet(url).reply(200, data);
    const { result, waitForNextUpdate } = renderHook(() =>
      // I'm not wrapping the hook in this example, but if you do just replace
      // this with your custom hook and change what result.current returns
      useAxios({ method: "GET", url }, { manual: true })
    );
    await act(async () => {
      const [, execute] = result.current;
      execute();
      await waitForNextUpdate();
    });
    expect(result.current).toEqual([
      expect.objectContaining({ data }),
      expect.any(Function)
    ]);
  });
});
```

**Comment by lmiguelvargasf** [comment]
@LiaoJimmy , how does your code looks after mocking `axios-hooks` response?

**Comment by LiaoJimmy** [comment]
> @LiaoJimmy , how does your code looks after mocking `axios-hooks` response?

I think mock `axios-hooks` response is not a good solution.
For mock API response, we have better choice like Mirage JS (https://miragejs.com/).
It has many features and better developer experience.

**Comment by simoneb** [comment]
@LiaoJimmy @lmiguelvargasf @tgfischer mocking this library with jest is as easy as:

```jsx
import useAxios from 'axios-hooks'

jest.mock('axios-hooks')

// in your test
useAxios.mockReturnValue([{ data: { ... } }])
```

**Comment by KristianLonergan** [comment]
@simoneb how would you go about mocking axios-hooks when you have multiple instances of useAxios within a file?
For example:
```
const [{ data: booksData, loading: booksLoading }] = useAxios('/books');
const [{ data: addBookData, loading: addBookLoading }] = useAxios({url: '/addBook', method: 'POST'}, {manual: true});
```

**Comment by simoneb** [comment]
@KristianLonergan in the same way as you would mock a jest mock function which is called multiple times, see [here](https://jestjs.io/docs/en/mock-functions.html#mock-return-values).

I appreciate this is not ideal so I'll be looking into #218 that's been opened a few days ago. But, there are ways to mock this easily already.

**Comment by dkershner6** [comment]
Just to throw out there, and it is not mutally exclusive with #218 ...

I really appreciate this library, and I had some more complicated mocking scenarios that required several useAxios hooks to be used with each other, relying on one another.  The ordered mocking method above falls down when firing off items in random order and such.

So, I created a library to handle every scenario I (and the rest of my company) needed, and you all are free to use it as well: https://www.npmjs.com/package/axios-hooks-mock

It's an implementation that should work well for both simple and complex scenarios and abstracts most of the testing boilerplate away.

Tagging @simoneb just to let him know.
