### ISSUE TITLE
UseCache not working

### ISSUE THREAD

**Issue by pacocom** [simoneb/axios-hooks#354]
If I use:
```js
  const [{ data, loading, error}, execute] = useAxios(
    {
      url: 'https://reqres.in/api/users/1',
      method: 'PUT'
    },
    { manual: true, useCache: true }
  )

const handleClick = () => {
execute()
}
```
Request cache not working.

If I use:
```js
  const [{ data, loading, error}, execute] = useAxios(
    {
      url: 'https://reqres.in/api/users/1',
      method: 'PUT'
    },
    { manual: true }
  )

const handleClick = () => {
execute(undefined, { useCache: true })
}
```
Why Do I need to use "useCache" in execute function to cache request?

Thanks!

**Comment by simoneb** [comment]
Because the first option provided in the hook usage applies to when the hook triggers a request, the second option used in the execute function applies when you invoke that function and is false by default. This is explained in the docs.

**Comment by pacocom** [comment]
Obviously, I read the documentation before write the question!

Sorry. but I didn't understand why useCache of hooks is different to useCache of execute function!

Thank!

**Comment by simoneb** [comment]
@pacocom they serve the same purpose but they have different defaults, which are independent from each other. It's true in the hook usage, false in the execute function usage.
