### ISSUE TITLE
axios-hooks and react-adal

### ISSUE THREAD

**Issue by sourdenis** [simoneb/axios-hooks#367]
Hi!
First, thanks for a great hook :).
But I'm having problem with using it with react-adal - as MS AAD token times out usually in 5 min I need to update the token in the request header everytime the request is made (the refershing of the token is done by react-adal component in the background).
The problem is that the react-adal method for getting the current token is async and I'm struggling to get the code to work correctly. It may come down to my lack of knowledge in JS and ReactJS :)

Right now I made a custom hook that looks like this:

```
import useAxios from 'axios-hooks';
import { adalAddApiHeaderAuht } from '../../adalConfig'; // method that return the header conf object with Authorization token
import { useState, useEffect, useRef } from 'react';

const useServicesRequest = (reqURI, method = 'get', manual = false, body) => {
    let localState = { data: null, loading: false, error: null };
    const [axiosConf, setAxiosConf] = useState({
        conf: { url: '', method: method },
        manual: true,
    });
    let reLoad = null;

    if (body !== undefined)
        setAxiosConf(() => {
            axiosConf.conf.data = body;
        });

    async function wHeaderConf() {
        const l = await adalAddApiHeaderAuht(axiosConf.conf);
        setAxiosConf(() => ({ conf: l, manual }));
    }
    useEffect(() => {
        wHeaderConf();
    }, []);

    [localState, reLoad] = useAxios(axiosConf.conf, {
        manual: axiosConf.manual,
    });

    return [localState, reLoad];
};
```

**Comment by simoneb** [comment]
You can find an example of how to do it in [this code sandbox](https://codesandbox.io/s/axios-hooks-authentication-zyeyh?file=/src/index.js). I added the example to the readme

**Comment by sourdenis** [comment]
thank you :)
