### ISSUE TITLE
UnhandledPromiseRejectionWarning on Server side

### ISSUE THREAD

**Issue by gtolarc** [simoneb/axios-hooks#38]
If I use useAxios on nextjs server side, if the call returns an error, an unhandled promise error will occur.
Is there any error handling in the execution of the ssrPromises array?

```
(node:73458) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/Users/mk/dev/workspace/dapps/gione/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/mk/dev/workspace/dapps/gione/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/mk/dev/workspace/dapps/gione/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:73458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:73458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by simoneb** [comment]
There currently isn't, as you can see here

https://github.com/simoneb/axios-hooks/blob/9f5a6cedf50b4326c779e3578bdd8ed364e49853/src/index.js#L36-L44

What would be a reasonable thing to do? I guess not much except swallowing the exception.

**Comment by gtolarc** [comment]
I think I misjudged the point where the error message appeared.
https://github.com/simoneb/axios-hooks/blob/8593fcd8567f41f47807b31d9d73a5855e7fc907/src/index.js#L134
Even though this code is executed on the server side even if it is option:manual.
Could you modify it to exclude if option:manual? @simoneb

**Comment by simoneb** [comment]
yeah there's definitely a bug there. wanna send a PR perhaps? (with tests please)

**Comment by simoneb** [comment]
The bug with manual requests being executed on the server is now addresses in version 1.4.1
