### ISSUE TITLE
uncaught (in promise) 

### ISSUE THREAD

**Issue by oddball** [simoneb/axios-hooks#383]
In my React app, with version 2.4.0, i got:

<img width="706" alt="Screenshot 2021-03-06 at 13 38 24" src="https://user-images.githubusercontent.com/1045794/110208630-a8f1c100-7e88-11eb-83f9-80b907be5c43.png">

``` 
uncaught (in promise) Cancel {message: undefined} (index):1
```

Downgraded to 2.3.0 and had no problems

**Comment by simoneb** [comment]
Can you provide an example to reproduce the problem?

**Comment by oddball** [comment]
Sadly no. I got no debugging information at all

**Comment by simoneb** [comment]
This is now fixed in 2.4.1

**Comment by HonzaTuron** [comment]
@simoneb unfortunately I'm still able to reproduce this issue in 3.0.0. Uncaught promise error is shown once component is unmounted and response started but didn't finish yet.

**Comment by simoneb** [comment]
@HonzaTuron do you have a repro?

**Comment by HonzaTuron** [comment]
@simoneb I have following:

- useAxios hook (manual: false) in another custom hook
- Custom hook mounted in component

Then, once component is unmounted and request didn't finish yet, promise error shows in console.
