### ISSUE TITLE
CORS Header ‘Access-Control-Allow-Origin’  missing

### ISSUE THREAD

**Issue by rchavezj** [simoneb/axios-hooks#385]
Not so much of an issue but curious how we can configure the http request to support CORS header ‘Access-Control-Allow-Origin’ missing? When I execute the request the backend (python) I get all of my data and I'm trying to connect the api to the front end (react with axios-hooks) and i get an error for not enabling the CORS header

**Comment by simoneb** [comment]
This has nothing to do with axios-hooks. CORS needs to be enabled in the server.

**Comment by rchavezj** [comment]
Thats the weird part because i have http response of 200 in one language but not the same for react axios-hooks with 400

**Comment by simoneb** [comment]
That it's not a CORS problem.

**Comment by rchavezj** [comment]
Sounds like it's a proxy configuration issue. Someone updated the proxy on react package.json file and the CORS issue was fixed even tho it's not a server related issue. 

https://www.youtube.com/watch?v=hxyp_LkKDdk&t=693s&ab_channel=HongLy
