### ISSUE TITLE
Changes required for 2.5.0

### ISSUE THREAD

**Issue by MichielDeMey** [simoneb/axios-hooks#386]
Hey guys

I noticed the new 2.5.0 version removes the JSON serialization, which is a really nice performance boost!
However, as a side-effect I have a component with an infinite re-render when upgrading.

I investigated this and found the part that was causing the re-renders.

Before, I had the following:
```ts
const [{ data, error }, getData] = useAxios({
  url: '/foo',
  transformResponse: (data) => {
    const { foo } = JSON.parse(data);
    return foo.filter(someFilterFuncWithStateVariables);
  },
});
```

The issue here is that I was lazy and I used an anonymous function (with a state variable in it) to transform the response which will trigger a change every re-render.

It's easily fixed from my end by using a `useCallback` to memoize the function though.

```ts
const transformResponse = useCallback(
  (data) => {
    const { foo } = JSON.parse(data);
    return foo.filter(someFilterFuncWithStateVariables);
  },
  [someFilterFuncWithStateVariables]
);
const [{ data, error }, getData] = useAxios({
  url: '/foo',
  transformResponse,
});
```

Just documenting this change out there for the lazy devs like me that used an anonymous function with some state variables in the Axios config. 😉

**Comment by simoneb** [comment]
Fair point, thanks for bringing this up. I added this to the docs [here](https://github.com/simoneb/axios-hooks#refresh-behavior) as it's worth mentioning explicitly.
