### ISSUE TITLE
No opportunity to intercept headers

### ISSUE THREAD

**Issue by Anatoliy13Kravchenko** [simoneb/axios-hooks#391]
There is no opportunity to intercept headers in makeUseAxios. For example i made some exemplar from makeUseAxios factory with some appropriate strict settings, but in one of cases i only need to add/change header 'Accept': 'text/csv ' or else.

Example:

`import useAxios from './useAxios';
const useFetchProductsFile = (url: string) => {

    const [{ error, response, loading }, reFetch] = useAxios({
        url:  '/dev/products/csv?${url}',
        method: 'GET',
        headers: {
            accept: 'text/csv'
        },
        responseType: 'blob',
    }, {
        manual: true
    });

    return {
        fileError: error,
        fileResponse: response,
        fileLoading: loading,
        fileRefetch: reFetch
    };
};
export default useFetchProductsFile;`

If you can help me/fix/ would be great. Thanks in advance)

**Comment by simoneb** [comment]
Can you put together an example which reproduces the issue?

**Comment by Anatoliy13Kravchenko** [comment]
https://codesandbox.io/s/blue-platform-ytps8
and as you can see, Headers, in our case exactly Accept, the same but not 'text/csv'
![image](https://user-images.githubusercontent.com/20690028/113120466-4935ce00-921a-11eb-922f-6afac4f42b07.png)

**Comment by simoneb** [comment]
I set up a repro starting from your example, which shows that request headers are sent correctly. 

https://codesandbox.io/s/funny-haibt-13mj0

If you're experiencing an issue it must be something in your code. I'm going to close this issue.

**Comment by Anatoliy13Kravchenko** [comment]
Sorry, that you've wasted time, i suppose it's because of axios.interceptors. Great package  ,)

**Comment by simoneb** [comment]
No problem, let me know if you figure out the issue.
