### ISSUE TITLE
Add interceptors to configuration object? Are the docs wrong?

### ISSUE THREAD

**Issue by rsdrsd** [simoneb/axios-hooks#393]
The docs state the following:

> Because of this, it's important to make sure that the arguments to useAxios preserve deep equality across component renders. This is often the case unless functions (e.g. axios **interceptors** or transformers) are provided to a configuration object. In that case, those functions need to be memoized or they will trigger a request execution at each render, leading to an infinite loop.

But for me it's no where to find how I can add an interceptor to a configuration object. I am wondering if this is even possible. What I can read from the official axios docs is that I only can add interceptors to the an axios instance using something like: ```axios.interceptors.request.use()```. So I have a few questions:

1. If I use ```axios.interceptors.request.use()``` do I need to use `useCallback`. In my opinion I don't need to use `useCallback` because it's outside the render function of React.
2. How can I add interceptors to a configuration object which is inserted in `useAxios`?

**Comment by simoneb** [comment]
You can use a custom axios instance, see [docs](https://github.com/simoneb/axios-hooks#makeuseaxios-cache-axios-defaultoptions-)

**Comment by rsdrsd** [comment]
Well maybe you should remove the `axios interceptors` example from the docs, because this isn't possible and you don't need to memoize this function for this. Or what do you mean with this?

**Comment by simoneb** [comment]
done
