### ISSUE TITLE
transformResponse callback is not called.

### ISSUE THREAD

**Issue by B-Esmaili** [simoneb/axios-hooks#395]
I make a simple request with this library, response is received with 200 status but `transformResponse`  is not called.Following is my code snippet:

```
 const [{ loading, error},refetch] = useAxios({
    url,
    transformResponse: function(data:TServerData){       
      setCurrentFetch((f: DataFetchInfo<TServerData, TError> | null) => ({
        page: f!?.page,
        data,
        status: DataFecthStatus.Done,
      }));

      return (data as unknown) as TData;
    }
  },{manual:true, })
```
What is wrong with my code?

Here is a link for [sandbox](https://codesandbox.io/s/infallible-moon-bbwf0).

**Comment by simoneb** [comment]
It goes into an infinite loop. See https://github.com/simoneb/axios-hooks#refresh-behavior
