### ISSUE TITLE
Request is cancelled when setting paramsSerializer as anonymous function

### ISSUE THREAD

**Issue by frankie567** [simoneb/axios-hooks#396]
# Context

When setting the option `paramsSerializer` in the options as an anonymous function, the request is immediately cancelled after having being triggered.

If the function is defined outside (not in a component or a hook), it doesn't happen. It also doesn't happen if the function is wrapped inside a `useCallback` hook.

I suspect here that `axios-hooks` isn't able to detect that the function is the same if defined as an anonymous function and therefore triggers a hook refresh.

I had code which was working well before with an anonymous function, so I think it was introcuded quite recently (>2.5.0)

# To reproduce

1. Declare a request with `useAxios` and set some `params` and `paramsSerializer` as anonymous function.
2. Trigger the request
3. The request is cancelled

Example on CodeSandbox: https://codesandbox.io/s/axios-hooks-paramsserializer-cancel-r69o2

# Versions

*  axios: 0.21.1
* axios-hooks: 2.6.1
* react: 16.13.1

**Comment by simoneb** [comment]
https://github.com/simoneb/axios-hooks#refresh-behavior

**Comment by frankie567** [comment]
Sorry, I didn't pay attention to this 😖 Thanks for the quick pointer!

**Comment by simoneb** [comment]
Fair point though, it was a breaking change introduced in a non-major version.
