### ISSUE TITLE
[Feature Request] Clear cache

### ISSUE THREAD

**Issue by Eshaan7** [simoneb/axios-hooks#397]
Not sure if it is in the scope, but I'd like a way/utility function that clears all cache. An example use case would be clearing all cache when the user logs out.

**Comment by simoneb** [comment]
It's documented but `useAxios` exposes a `clearCache` function, see https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L25.

A way to do it in a documented way is to provide a custom cache via either `configure` or `makeUseAxios`.
