### ISSUE TITLE
Support for Parallel Requests 

### ISSUE THREAD

**Issue by Ashwinvalento** [simoneb/axios-hooks#399]
My Scenario is as follows:  I need to make 2 GET API calls simultaneously on component mount and wait for both to finish and only then proceed with other logic.

Is there a way to make parallel API requests directly using axios-hooks or do I need to manage it myself?

**Comment by simoneb** [comment]
Two HTTP requests are inherently two distinct "things", so they have to be handled explicitly. It shouldn't be too hard, you can use the loading flags of the two requests to check when they've completed, for example.
