### ISSUE TITLE
SSR: Isolate clients

### ISSUE THREAD

**Issue by braska** [simoneb/axios-hooks#4]
Looks like there is no isolation between clients.

All promises will be pushed to the one array:

https://github.com/simoneb/axios-hooks/blob/2c4f0e8d984d760999729708daf5447d4690e068/src/index.js#L14

So, there is unexpected behavior when multiple requests will be received.

`const cache = await serializeCache()` will wait for promises created by different requests.

**Comment by simoneb** [comment]
That's the purpose exactly, if I understand what you mean. This is for SSR, where we need to wait for alla requests to complete before rendering the application on the server.

**Comment by braska** [comment]
Yes, I understood the purpose of `ssrPromises` array, but...

Let's say:
1. I deployed application that uses `axios-hooks` (for example on AWS).
2. I am trying to open my application from my laptop and from smartphone on the same time. So, there are two requests for server.
3. Server receiving first request and starting to push promises to `ssrPromises`.
4. While server processes the first request (not all promises resolved or even `React.renderToString` is still executing), another request is received (it is possible because Node.js is async by the nature and uses non-blocking I/O model) and promises related to second request will be pushed to `ssrPromises`.
5. When `await serializeCache()` will be called for the first request, it will be in pending state until all promises (including promises related to second request) will be resolved.
6. In this `const cache = ...` for the first request will contains some data related to second request.


This is a pretty common issue across React ecosystem. So there is known solution.

For example, https://github.com/nfl/react-helmet suffer from this kind of problem too. I am very surprised that `react-helmet` didn't resolved this problem for all years of existing. But there is existing fork that solves problem: https://github.com/staylor/react-helmet-async.

I am trying to say that this lib (`axios-hooks`) needs something like what `react-helmet-async` do to isolate request contexts.

**Comment by simoneb** [comment]
Oh wow, you have a very good point indeed. I'll think of something, haven't done something like this before but I'm sure there must be a reasonably easy solution. Thanks for reporting!
