### ISSUE TITLE
How to get response status in case of 401 error?

### ISSUE THREAD

**Issue by B-Esmaili** [simoneb/axios-hooks#401]
When I make a request and server response with a 401 error there is no way to get the status code from the response because response is undefined.

**Comment by simoneb** [comment]
There's a section with a link to an example about error handling in the docs.

**Comment by B-Esmaili** [comment]
I want to get a status code from an error, not an error message containing status ocde.

**Comment by simoneb** [comment]
The error object is the axios error, meaning that if the error has a response the status code will be in the response property. See https://github.com/axios/axios#handling-errors.

I've also updated the example in codesanbox to show the error's status code.

**Comment by B-Esmaili** [comment]
If mock-adapter is valid here I tested with it and I didn't get any status code in the error object. This is [link](https://codesandbox.io/s/axios-hooks-error-handling-forked-jksfb?file=/src/index.js) to the sandbox demo.
