### ISSUE TITLE
Fetch on cache expired

### ISSUE THREAD

**Issue by dandin84** [simoneb/axios-hooks#406]
Hi, I probably missing something....

I am trying to reduce the cache maxAge hopping that on cache expired the data will fetch from the server instead of displaying from the cache. For testing I reduce the cache to 3 minutes but after 3 minutes there was no api call when reaching the page (unless I hard reload the app).

Is there a way to make sure that when the cache expired, the api call will invoke?

**This is my configuration:**
![image](https://user-images.githubusercontent.com/6383184/118301283-8e247400-b4eb-11eb-8f35-7c48f6eb9f01.png)

**This is the api call:**
![image](https://user-images.githubusercontent.com/6383184/118301440-b7450480-b4eb-11eb-847b-eac5c18e827e.png)

**Comment by simoneb** [comment]
> Is there a way to make sure that when the cache expired, the api call will invoke?

The simplest way is to use the cache correctly. See the docs: https://www.npmjs.com/package/lru-cache

**Comment by dandin84** [comment]
Sorry, apparently I had a misspell. Thanks for you quick reply and the cool library 👍
