### ISSUE TITLE
Specifying validateStatus on a manual request, instantly cancels the request

### ISSUE THREAD

**Issue by ymor** [simoneb/axios-hooks#413]
Example codesandbox:
https://codesandbox.io/s/axios-hooks-manual-request-forked-dvl0t?file=/src/index.js

Issue:
When the validateStatus is configured at the useAxios level the request is automatically cancelled when you click "update data".   

Expectation:
The request should not be cancelled.

Workaround:
Move validateStatus into the execution part of the manual request

**Comment by simoneb** [comment]
see https://github.com/simoneb/axios-hooks/#refresh-behavior

**Comment by ymor** [comment]
Thanks, Totally makes sense for an automatic request, but should this be the behaviour on a manual request?

**Comment by simoneb** [comment]
debatable indeed. that's just how it works now
