### ISSUE TITLE
Pass auth0 token using Auth0 React SDK

### ISSUE THREAD

**Issue by gutisalex** [simoneb/axios-hooks#418]
Hey, I am using auth0 to secure my API. Auth0 provides the Auth0 React SDK which uses context and hooks.  I need the token set into the authorization header when fetching data from my API. Problem is getting the accesToken happens via hooks as well and is async. So I would have to get the token via useEffect and pass it to useAxios in the header. Unfortunatly this cannot work... Some knows a workaround for this?

Until this point I was creating an axios instance and used a custom function which takes the token as a param:

```ts
const instance = axios.create({
  baseURL: process.env.REACT_APP_SERVER_BASE_URL,
});

export const authorized = (token: string) => {
  instance.defaults.headers.common["Authorization"] = `Bearer ${token}`;
  return instance;
};
```

In my own custom http hook I used a useCallBack function to fetch the token and passed that to my authorized http function. 

Any ideas?

**Comment by simoneb** [comment]
Did you check out the authentication example in the docs?

**Comment by gutisalex** [comment]
Yes I did but first off I would not want to put any sensitive data into local storage and second in this context I dont have access to the token of auth0 at all. They use a hook to get the token:

```ts
const { user, isAuthenticated, getAccessTokenSilently } = useAuth0();
```

https://auth0.com/docs/quickstart/spa/react/02-calling-an-api#get-an-access-token

**Comment by simoneb** [comment]
You don't have to use local storage once you get it, you can store it anywhere. This is not a question about the library anyway, closing.
