### ISSUE TITLE
useAxios "execute" not returning how the documentation suggests.

### ISSUE THREAD

**Issue by michaelryancaputo** [simoneb/axios-hooks#422]
Hello!
Based on the documentation located [here](https://github.com/simoneb/axios-hooks#useaxiosurlconfig-options), I would expect the `execute` call of `useAxios` to return the response value like this:

```
  const [
    { error: submitError },
    submitPut,
  ] = useAxios(
    {
      method: "PUT",
      url: 'URL',
    },
    { manual: true },
  );

  /// some other code

  const onSubmit = () => {
    // I would expect response to be available here so the response could remain
    // scoped to the function where it's called.
    const response = await submitPut();

    if (response.thing) {
      // do a thing
    }

    // dont do a thing
  }
```

I understand that there is the response `data` provided within the object (next to `error`) - just would like to point out, that the docs read in a way where the above should be possible. I guess a solution would be to improve the docs to be more indicative of where the response can be accessed.

Love the module!!

**Comment by simoneb** [comment]
The docs look correct to me. Awaiting the invocation of the execute function returns:

>  The whole [success response](https://github.com/axios/axios#response-schema) object.
