### ISSUE TITLE
Refetch doesn't pull out newly posted data

### ISSUE THREAD

**Issue by Lekha30** [simoneb/axios-hooks#489]
I am Posting new Data manually and triggering a refetch after posting. The refetch is not fetching the latest data. It only has the stale data. 

Any help is appreciated.

**Comment by simoneb** [comment]
You must skip the cache, this is thoroughly described in the docs

**Comment by kwiat1990** [comment]
I have added `useCache: false` to a sandbox with the manually triggered request but the old data doesn't refresh. I was expecting something like what we get in `swr` package when calling `mutate`.
