### ISSUE TITLE
How to do the post request using this useAxios hook

### ISSUE THREAD

**Issue by raviSussol** [simoneb/axios-hooks#524]
The guide or example shown in the home page of this repo has just an example for the `put` request but its data is also depends on the data fetched by the `get` request at initial when using the `useAxios` at the top first time.
```
const [
    { data, loading: putLoading, error: putError },
    executePut
  ] = useAxios(
    {
      url: 'https://reqres.in/api/users/1',
      method: 'PUT'
    },
    { manual: true }
  )
```
 So I was wondering about how can I do the `post` request without using the `get` request at initial at the top of the react component but directly use the `useAxios` hook with configs for the post and then when I call the executePost method then its `data` and the `error` state variables gets filled up. Say something like below:

```
import React from 'react'
import ReactDOM from 'react-dom'
import useAxios from 'axios-hooks'

const postConfig = {
  url: '/authenticate',
  method: 'POST',
  auth: { username: 'test', password: 'pass' }
};

function App() {
  const [{ data, error }, executePost] = useAxios(postConfig, { manual: true });
  ...
  const handleLogin = async () => {
    executePost();
    return { data, error };
  };
}

const rootElement = document.getElementById('root');
ReactDOM.render(<App />, rootElement);

```

**Comment by simoneb** [comment]
Can you clarify what you're trying to do? An annotated example on codesandbox will do.

**Comment by raviSussol** [comment]
@simoneb Never mind. I was actually playing with this [example](https://codesandbox.io/s/axioshooks-manual-request-bq9w4) - trying to modifying with the `POST` request and then wanted to see the output in the state variables (like `data`, `error`, ...) right after its call in the `executePost` method without using the `useAxios` hook with `get` at the top. Then I caught those state variables thrown `undefined` values at first button click then only showed values from the second click so was wondering how it could have been used properly other than a `PUT` request. But when I tried to make an example codes separately in the codesandbox then realised that those state variables have no issues rendering in the UI and also its the side effect that it needed to handle to catch their values immediately in the function. [Here](https://codesandbox.io/s/focused-bash-b3mff?file=/src/App.js)

So no issue - sorry to bother you :-). Please feel free to close it.

**Comment by simoneb** [comment]
No problem.
