### ISSUE TITLE
autoCancel:false not working

### ISSUE THREAD

**Issue by gkmadushan** [simoneb/axios-hooks#609]
In some specific requests we want to prevent autoCancel when navigating to different route thought the react-router-dom. 

sample code

`const [{ data, loading, error, response }, requestHandler] = useAPI(
    {method: "POST",
      url: "/selections",
      data: {
        id: id,
      }},
    { manual: true, autoCancel:false }
  );`

another try with configuration
`
const defaultOptions  = { manual: false, useCache: true, ssr: true, autoCancel: false}
configure({ axios, cache, defaultOptions});
`
But both methods didn't work. 

Even directly changing node module like below
`
const DEFAULT_OPTIONS = {
  manual: false,
  useCache: true,
  ssr: true,
  autoCancel: false
}
`

Appreciate if you can look into this.

**Comment by simoneb** [comment]
Can you provide a repro?
