### ISSUE TITLE
Feature request: fetchPolicy

### ISSUE THREAD

**Issue by stevewillard** [simoneb/axios-hooks#7]
I'm running into a scenario where I could benefit from something similar to Apollo's `fetchPolicy`: https://www.apollographql.com/docs/react/api/react-apollo/

Specifically, the `cache-and-network` variant is the most useful to me, where I want to load data from the cache, but also make a network request to fetch potential updates.

Do you think it's possible to add an option like this? Ideally, it's something you could configure globally as part of `configure`, but also override on a per-hook basis.

**Comment by simoneb** [comment]
Isn't this case already covered by the normal behavior of the hook together with the second item of the array returned by the hook invocation (sometimes called `refetch`) which allows you to issue the request again?

**Comment by stevewillard** [comment]
Yeah, I think that would work, but I was hoping to avoid explicitly recalling refetch.

Here's the scenario I'm working with:

I have a table of data with pagination controls, where the `page` is stored in the URL as a query parameter. I'm using this hook to parse/set that query parameter: https://github.com/pbeshai/use-query-params

So, I have something like this:
```
const [page = 1, setPage] = useQueryParam('page', NumberParam);

const [{ data, loading, error }, refetch] = useAxios({
    url: 'my_api_route',
    params: {
        page,
    },
});
```

When I click on a new page, I call `setPage` which updates the URL, which re-renders the component and the axios hook will fetch the new page of data.

If I navigate back to a page I have already seen, `axios-hooks` will read from the cache, but what I want is to read from the cache and also issue a network request. I could definitely achieve this by calling `refetch` as part of the `onClick` for the pagination control which calls `setPage`, but I was hoping to do this automatically.

**Comment by simoneb** [comment]
I see what you mean. Yes it would make sense to have something like this, but because it would be quite some additional complexity to add to the package, which at the current time is overall quite simple, and because the workaround in your case is super simple as well, I wouldn't consider this a priority. I mean it's complexity added to the package versus a one line of code on the package user.
