### ISSUE TITLE
Uncaught Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by jackhelodeon** [simoneb/axios-hooks#735]
I'm trying to centralise the API endpoints into a single file and then import them however it seems this library doesn't support that. Is there any other way of achieving my goal/am i going the wrong way about it or is it possible for this to be a future enhancement? 

I get this error from the code below
`Uncaught Error: Objects are not valid as a React child (found: Error: Request failed with status code 404). If you meant to render a collection of children, use an array instead.`

My code:
(api.js)
```
const API_URL = "https://jsonplaceholder.typicode.com";

export function getUsersEndpoint() {
  return API_URL + "/users";
}
```
customers.jsx)
```
import { getUsersEndpoint } from "../../api";

function Customers() {
  console.log(getUsersEndpoint()); // outputs string
  const [{ data, loading, error }, refetch] = useAxios(getUsersEndpoint());
........blah blah
}
```

Thanks

Also, if i point to a broken 404 URL say for example below... I get a 404 console log but then i get the errors below.
```
  const [{ data, loading, error }, refetch] = useAxios(
    "https://jsonplaceholder.typicode.com/uuss"
  );
```
```
              <button onClick={refetch}>refetch</button>
              {loading && !error ? (
                <LoadingOverlay visible={loading} />
              ) : error ? (
                <div className="errorMessage">{error}</div>
              ) : (
                <pre>{JSON.stringify(data, null, 4)}</pre>
              )}
```
<img width="955" alt="image" src="https://user-images.githubusercontent.com/75576058/153253807-e76a09b1-916b-48d3-ad3c-5639d066fdeb.png">

Live example:
https://codesandbox.io/s/weathered-dust-99coj?file=/src/App.js

**Comment by simoneb** [comment]
This is a problem in your code. You're trying to render `error` which is an object, hence React complains.

```
<div className="errorMessage">{error}</div>
```
