### ISSUE TITLE
Feature Request: Clearing specific cache key

### ISSUE THREAD

**Issue by vmlopezr** [simoneb/axios-hooks#744]
When using lru cache, it looks like the config object is stringified for the key. 

https://github.com/simoneb/axios-hooks/blob/6f060a20db7cb4ca70bd06315e05ff0a847ebd4d/src/index.js#L48

In my project i have a need to clear the cached value so that i can fetch new items. At the moment the way we're doing this is by purging the entire cache.

Would it be possible to either:
1. Add a config option for custom cache key, which we can reference easily.
2. Return a method just like the cancel method, which would clear only the cache key?

**Comment by samavati** [comment]
Is this one still needed? 🤔 seems interesting to me :)

**Comment by simoneb** [comment]
There don't seem to be many people asking for this feature, but I'm not against introducing it either.

**Comment by samavati** [comment]
> There don't seem to be many people asking for this feature, but I'm not against introducing it either.

@simoneb could you please assign this one to me?
