### ISSUE TITLE
Canceled message undefined when using onUploadProgress config

### ISSUE THREAD

**Issue by cuongurus** [simoneb/axios-hooks#755]
Request got canceled with message undefined when using onUploadProgress config from version 2.5.0 and above, 2.4.1 work fine
```js
const [
    { data: postData, loading: postLoading, error: postError },
    executePost,
    cancelUpload,
  ] = useAxios(
    {
      url: UPLOAD_API,
      method: 'POST',
      headers: {
        'Content-Type': 'multipart/form-data',
      },
      onUploadProgress: (progress) => {
        const percent = Math.round((progress.loaded / progress.total) * 100);
        setUploading(percent);
      },
    },
    {
      manual: true,
    },
  );
```

[CodeSanbox example](https://codesandbox.io/s/axios-hooks-manual-request-forked-crc7ik?file=/src/index.js)

**Comment by singleseeker** [comment]
have the same issue.

**Comment by singleseeker** [comment]
@simoneb sorry to trouble you, any idea about that?

**Comment by simoneb** [comment]
See the notes in https://github.com/simoneb/axios-hooks#refresh-behavior. IoW, functions provided as options need to be memoized. I'll close this issue because I think that's the issue, but please reopen if that doesn't solve it.
