### ISSUE TITLE
'error' stays true in 'options change detection' example

### ISSUE THREAD

**Issue by rohan-rest-art** [simoneb/axios-hooks#766]
The examples block contains a link 'Options change detection':
https://codesandbox.io/s/axios-hooks-options-change-v23tl
I found an issue in this example.

How to reproduce:
* Follow the link above.
* Submit a request with user id '1'.
* Shows data for user id '1'. Works good.
* Submit a request with user id '2'.
* Shows data for user id '2'. Works good.
* Submit a request with user id '2222222222222222'.
* Shows an error and data for user id '2'. Why hasn't 'data' changed? Looks weird but ok.
* Submit a request with user id '1' again.
* Shows an error and data for user id '1'. Why is 'error' still truthy?

Probably the issue has the same cause as https://github.com/simoneb/axios-hooks/issues/372

**Comment by simoneb** [comment]
Thanks for reporting this. This looks like a bug in the cache. Would you like to submit a PR to fix it?

**Comment by KyorCode** [comment]
Its still a bug and a pretty annoying one. :/

**Comment by simoneb** [comment]
This is now fixed, lmk if the new version works for you
