### ISSUE TITLE
error is not reset if subsequent request succeeds

### ISSUE THREAD

**Issue by stevewillard** [simoneb/axios-hooks#8]
If you make a request and it returns an error, and then make a new request, it won't reset error.

I think it's just a matter of resetting `error` during `REQUEST_START`.

**Comment by simoneb** [comment]
thanks for reporting @stevewillard. can you submit a PR for this perhaps?

**Comment by stevewillard** [comment]
Sure, I'll take a stab at it when I get a chance.

**Comment by 8enSmith** [comment]
> Sure, I'll take a stab at it when I get a chance.

I encountered the same issue and decided to create a PR to fix it. Pretty sure it fixes the issue (test proves the case anyhow!). Another set of eyes reviewing the PR wont harm.

**Comment by simoneb** [comment]
closed via #15 and fixed in version 1.1.3
