### ISSUE TITLE
Suggestion: upgrade lru-cache and use lru-cache/browser

### ISSUE THREAD

**Issue by Resetand** [simoneb/axios-hooks#845]
Hi, i'd like to suggest you to use the new version of lru-cache and start using `lru-cache/browser` instead of `lru-cache`

[lru-cache v7.4.0](https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#740)

**Comment by simoneb** [comment]
What's the advantage?

**Comment by Resetand** [comment]
`Add browser optimized webpack bundle, exposed as 'lru-cache/browser'`

**Comment by simoneb** [comment]
@Resetand Would you like to send a PR to do this?

**Comment by simoneb** [comment]
This is now solved in v4, by upgrading to the latest lru-cache which, by now, has removed the browser specific export
