### ISSUE TITLE
Feature request: Don't request the same query twice while in flight

### ISSUE THREAD

**Issue by stevewillard** [simoneb/axios-hooks#9]
I imagine this will be a bit complicated to implement, and is likely outside the scope of the library, but I figured I'd ask.

I'm working with a scenario where I would like to render an `<Avatar />` component which uses a `useAxios` hook within it to fetch information about the user. When rendering the same person's <Avatar /> man times on a single page, it issues a request for each one.

Do you think it would be possible to have subsequent requests wait for the initial request to resolve?

**Comment by Horat1us** [comment]
I suppose you need to create component to store user information. It should not be resolved in libraries like this.
You can use React Context for this case.

**Comment by conor909** [comment]
Yea it sounds like you just need to move the request to a parent and then pass the results to the Avatar and the Man Hours component, either through props or Context as Horat1us suggests
