### ISSUE TITLE
Handle 400 errors thrown by execute method

### ISSUE THREAD

**Issue by sujeet-agrahari** [simoneb/axios-hooks#902]
I know there is thread regarding the same issue. But it tells to silence the error. I don't understand why?

What if it throws `400`, a bad request, and we want to show the error message to the user? I am having the same issue.

```
const [{ error }, executeUpdate] = axiosHook(
    {
      ...ApiConfig.COURSE.UPDATE_COURSE,
    },
    { manual: true }
  );
```
...and here I call `executeUpdate`. I thought `error` will be the updated error but that line,`if (error) { ...do something }`,never gets executed as promise is rejected.

```
  const updateCourse = () => {
    handleSubmit(async (data) => {
      await executeUpdate({
        url: `${ApiConfig.COURSE.GET_COURSES.url}/${courseRow.id}`,
        data,
      });
      console.log(error);  // never gets called
      await refetchCourse();
    })();
  };
```

I want after `await executeUpdate()` it should update the error state variable and errors from it should be silenced. 
So that I could do,

```
if(error) {
  alert(error.message);
}
```
Is there a way we could silence the error from `executeUpdate` and get the error from state `error` variable instead?

It should maybe accept an option to silence the error default maybe false.

**Comment by simoneb** [comment]
wrap it in a try/catch block
