### ISSUE TITLE
How to record in state?

### ISSUE THREAD

**Issue by MichaelKheel** [simoneb/axios-hooks#93]
Hello, I wanted to use this module, but I didn’t understand how to write the state to the react hooks, because an error of endless re-rendering appears. In the usual use of axios, this was done in useEffect(), can show a simple example of how to record the state using your module ?

**Comment by simoneb** [comment]
Can you explain better what you're trying to do? You can find a few examples linked from the readme file, is your case not covered there?

**Comment by MichaelKheel** [comment]
This is my current state recording option. How do I rewrite this code so that it works with axios-hooks?

```
const [message, setMessage] = useState([]);

useEffect(() => {
	axios.get("/chat/main").then(res => {
		setMessage(res.data);
	});
}, []);
```

**Comment by simoneb** [comment]
That's a very simple use case, if you had read the first few lines of the documentation you would know how to do it. But here you go:

```
const [{ data: message }] = useAxios('/chat/main')
```

**Comment by MichaelKheel** [comment]
I understood this immediately, but this does not solve my problem with the state of the component.
There may be different code in the code for changing the state of the component, previously I did this simply using the state "setMessage()", but with your module, it won’t work out that way?

```
const ChatBlock = observer(() => {
	const { wsStore, authStore } = useStores();
	//const [message, setMessage] = useState([]);
	const [{ data: message, loading, error }] = useAxios('/chat/main');
	const El = useRef(null);

	useEffect(() => {
		let rt = wsStore.chatApp;
		rt = rt[rt.length-1];
		if(rt == null) return;

		let add = message.concat(rt["chatapp/sendmessage"]);
		setMessage(add);
	}, [wsStore.chatApp.length]);

	return(
		<div className="chat-block p-2" data-emoji="render" ref={El}>
		{
		!loading ? message.map((data, index) =>
			<ChatComment auth={authStore.auth} data={data} key={index} />
		) : ""}
		</div>
	);
});
```

**Comment by simoneb** [comment]
I'm sorry, but this has nothing to do with this package.
