### ISSUE TITLE
Multiple axios instances

### ISSUE THREAD

**Issue by CloudPower97** [simoneb/axios-hooks#98]
Hello @simoneb ,
is there a way to use multiple `axios` `instances`?
As far as I understand, [ `configure` ](https://github.com/simoneb/axios-hooks#configuration)accept a single instance.
Is there something I'm missing or is this funcionality not present ATM?
Is it going to be possible?
Maybe something like:
```js
import { configure } from 'axios-hooks'
import Axios from 'axios'

const firstInstance= Axios.create({
  baseURL: 'https://api.myjson.com/'
})

const secondInstance= Axios.create({
  baseURL: 'https://api.myjson.com/'
})

configure({ firstInstance, secondInstance })
//OR
//configure({axios: [firstInstance, secondInstance]})
```

(In either cases defaults to firstInstance if not specified)

and then use it like that:

```js
import useAxios from 'axios-hooks'

const [{ data: getData, loading: getLoading, error: getError }, manualFetch] = useAxios(
    'bins/820fc',
    {
         manual: true,
         instance: 'firstInstance'
    }
  )
```

This is my general idea.
Do you think that something along the lines of that is possible to achieve?
Thank you for your time!

**Comment by simoneb** [comment]
can you explain what would be the use case you're trying to accomplish?

**Comment by CloudPower97** [comment]
For example, in one of the projects I'm working on now, we have to make `AJAX` requests to both our private `API` and another external service.
To accomplish this task I usually create two custom instances of `Axios`, something along the lines of this:

#### ourApi.js
```js
import axios from 'axios';

export default axios.create({
  baseURL: 'http://our-api.com'
});
```

#### externalService.js
```js
import axios from 'axios';

export default axios.create({
  baseURL: 'http://external-service.com',
  params: {
    appid: 'mysecretkey'
  }
});
```

Now, without `axios-hooks` I would have imported the right instance in the needed component and that's it.

BUT, with `axios-hooks` we need to [`configure`](https://github.com/simoneb/axios-hooks#configuration) the `hook` prior using it.

But ATM there is no way to reference/use a different `instance` at my will, hence I opened this issue.
Thoughts?

**Comment by simoneb** [comment]
Yeah the scenario is a reasonable one, I think I would prefer to go with a hook creator, exported as a named export from the package, something along the lines of: 

```
import { makeUseAxios } from 'axios-hooks'

const useAxios = makeUseAxios({ ...base configuration })
```

What do you think?

**Comment by simoneb** [comment]
I'm working on a PR to add this, please check it out and let me know if you have thoughts. #100

**Comment by CloudPower97** [comment]
Hey, @simoneb , thanks for the quick `P.R`.
I'd like to have a glimpse of how we are supposed to `makeUseAxios`.
Do we have to configure it once? 
Do we have to use `makeUseAxios` and the returned `useAxios`  multiple times?

**Comment by simoneb** [comment]
@CloudPower97 see #100 and the updated README which includes an [example](https://codesandbox.io/s/axios-hooks-makeuseaxios-kfuym). Would this work for you?

**Comment by simoneb** [comment]
@CloudPower97 do you have any thoughts on this?

**Comment by CloudPower97** [comment]
Hey, @simoneb, sorry for this late answer.
I finally had a chance to try version `1.8.0-0`.
I've forked your CodeSandbox example and things went really smooth.
However, on the aforementioned project, I have got the following error:
```
Expected 0 type arguments, but got 1.ts(2558)
```
The code that is throwing this error is:
```javascript
  useApi<Colture[]>(
    {
      url: '/diz-coltures',
      ...config
    },
    options
  );
```
where `useApi` is what `makeUseAxios` gives me back, and `Colture` is a `TS` `interface`.
Worth noting that `useAxios<Colture[]>` is not throwing this error.

Anyway, thank you for your time, I do really appreciate!

**Comment by simoneb** [comment]
Can you please post the error in full? I can't see what the compiler is complaining about.

**Comment by CloudPower97** [comment]
Hey @simoneb, I've create a [sandbox](https://codesandbox.io/s/react-typescript-38m8p) as well, you can have a look at it whenever you want.
I've tried `useAxios` as well, and it has the same exact problem, but if I switch back to the previous version everything works fine.
It has to be something about this latest version.

**Comment by simoneb** [comment]
@CloudPower97 thanks for checking. There was indeed a problem with the TS type definition. Fixed in 1.8.0-2. Can you update and try again?

**Comment by CloudPower97** [comment]
@simoneb Everything works fine now, thank you!

**Comment by simoneb** [comment]
@CloudPower97 thanks for helping to troubleshoot the issue! I'll release this feature soon.
