### ISSUE TITLE
Still an issue with both `executeGet` and `execute` methods when executed manually

### ISSUE THREAD

**Issue by spogulis** [simoneb/axios-hooks#992]
Still an issue with both `executeGet` and `execute` methods returned by:

```
import { makeUseAxios } from 'axios-hooks'

const baseUrl = 'some api base url'
const url = 'some api get endpoint'

const createAxios = makeUseAxios({
  axios: axios.create({ baseURL: baseUrl })
})

const config: AxiosRequestConfig = {
    method,
    url: baseUrl + url,
    headers: {
      authorization: token ? 'Bearer ' + token : ''
    }
 }

const [{ data, loading, error }, execute] = createAxios(
    config,
    { manual: true }
)
```

Strangely post method works just fine whereas binding `executeGet` to `onClick` of a Button element does nothing.

_Originally posted by @spogulis in https://github.com/simoneb/axios-hooks/issues/82#issuecomment-1191573082_

**Comment by simoneb** [comment]
Please provide a repro, I already posted in the original request an example showing that it works.

**Comment by spogulis** [comment]
The repro you posted is not available.

> Please provide a repro, I already posted in the original issue an example showing that it works.

**Comment by simoneb** [comment]
Here's the repro. Note though that since you are reporting an issue, you are expected to provide a repro.

https://codesandbox.io/s/issue-82-repro-v0z6d6?file=/src/index.js

**Comment by spogulis** [comment]
Thank you.
